//! Generate the documentation that is derived from the code, and check it is current.
//!
//! Three things are generated. Each crate's `README.md` comes from its lib.rs rustdoc, with
//! registry buttons at the top, and is the crates.io page and the crate's landing doc; the
//! source is parsed with `syn`, so no nightly toolchain is needed. `docs/SUMMARY.md`, the
//! site's navigation, comes from the capability map in `docs/capabilities.toml`. And the
//! generated regions inside hand-written Markdown (the capability tables in the READMEs and
//! the site, and the code snippets spliced from test files) are re-rendered in place; see
//! [`regions`](crate::regions). `cargo xtask docs` writes all of it; `cargo xtask docs --check`
//! renders in memory, fails if any committed file is stale, and checks the capability map
//! against the crates, the Node packages, the Python modules, and the .NET types. It also renders
//! the Node packages' manifests and READMEs from that map. A hand-written crate README
//! (the dashboard's) is detected by the absence of the generated marker and left untouched.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use quote::ToTokens;
use syn::{Fields, ImplItem, Item, TraitItem, Visibility};

use crate::catalog::{Catalog, SITE};
use crate::{builds, buttons, packages, regions, theme, version};

/// Run the `docs` task: regenerate every derived file, or `--check` to verify they are in sync.
///
/// # Arguments
///
/// * `args` - `--check` verifies without writing; otherwise the files are regenerated.
///
/// # Returns
///
/// Success when the files were written, or when the check found them in sync.
pub fn run(args: &[String]) -> ExitCode {
    let check = args.iter().any(|arg| arg == "--check");
    match render_all() {
        Ok(readmes) => {
            let ok = if check {
                verify_files(&readmes)
            } else {
                write_files(&readmes)
            };
            if ok {
                ExitCode::SUCCESS
            } else {
                ExitCode::FAILURE
            }
        }
        Err(message) => {
            eprintln!("xtask docs: {message}");
            ExitCode::FAILURE
        }
    }
}

// The leading marker on a generated crate README; a README without it is hand-written (the
// dashboard's), so the generator leaves it alone.
const GEN_MARKER: &str = "<!-- Generated by `cargo xtask docs` from this crate's lib.rs; edit the crate doc, not this file. -->";

// Reads a crate's one-line `description` from its Cargo.toml, if present.
fn crate_description(krate: &str) -> Option<String> {
    let toml =
        fs::read_to_string(repo_root().join("crates").join(krate).join("Cargo.toml")).ok()?;
    for line in toml.lines() {
        if let Some(rest) = line.trim_start().strip_prefix("description") {
            if let Some(value) = rest.trim_start().strip_prefix('=') {
                let value = value.trim().trim_matches('"').trim();
                if !value.is_empty() {
                    return Some(value.to_owned());
                }
            }
        }
    }
    None
}

// The crates that also ship language bindings, with their package id on (npm, PyPI, NuGet),
// so the README links the registries that actually have the crate.
fn bindings(krate: &str) -> Option<(&'static str, &'static str, &'static str)> {
    match krate {
        "pamoja" => Some(("pamoja", "pamoja", "Pamoja")),
        "pamoja-core" => Some(("@pamoja/core", "pamoja-core", "Pamoja.Core")),
        _ => None,
    }
}

// One gradient button linking a registry, as inline HTML (renders on crates.io and GitHub).
fn button(href: &str, alt: &str, file: &str) -> String {
    format!(
        "<a href=\"{href}\"><img height=\"28\" alt=\"{alt}\" src=\"https://raw.githubusercontent.com/molexxxx/pamoja/main/.github/badges/{file}\"></a>"
    )
}

// The single per-crate README - the crates.io page and the crate's doc landing in one file:
// name, description, registry buttons, the lib.rs overview, and the items lib.rs defines. The
// full per-module API reference is docs.rs (linked by the buttons).
fn crate_readme(krate: &str, catalog: &Catalog, overview: &str, items: &str) -> String {
    let mut out = format!("{GEN_MARKER}\n\n# {krate}\n\n");
    if let Some(description) = crate_description(krate) {
        out.push_str(&description);
        out.push_str("\n\n");
    }
    let capability = catalog
        .capabilities
        .iter()
        .find(|capability| capability.crates.iter().any(|owned| owned == krate));
    let mut buttons = vec![button(
        &format!(
            "{SITE}/reference/rust/{}/index.html",
            krate.replace('-', "_")
        ),
        "API reference",
        "btn-api.svg",
    )];
    if let Some(guide) = capability.and_then(|capability| capability.guide.as_deref()) {
        buttons.push(button(
            &format!("{SITE}/{}.html", guide.trim_end_matches(".md")),
            "read the guide",
            "btn-guide.svg",
        ));
    }
    buttons.push(button(
        &format!("https://crates.io/crates/{krate}"),
        "crates.io",
        "btn-cratesio.svg",
    ));
    buttons.push(button(
        &format!("https://docs.rs/{krate}"),
        "docs.rs",
        "btn-docsrs.svg",
    ));
    if let Some((npm, pypi, nuget)) = bindings(krate) {
        buttons.push(button(
            &format!("https://www.npmjs.com/package/{npm}"),
            "npm",
            "btn-npm.svg",
        ));
        buttons.push(button(
            &format!("https://pypi.org/project/{pypi}/"),
            "PyPI",
            "btn-pypi.svg",
        ));
        buttons.push(button(
            &format!("https://www.nuget.org/packages/{nuget}"),
            "NuGet",
            "btn-nuget.svg",
        ));
    }
    out.push_str(&buttons.join("\n"));
    out.push_str("\n\n");
    // A capability crate is one of four packages for the same thing, so its page says where
    // the other three are; an engine crate has no counterpart and just names its reference.
    match capability {
        Some(capability) => out.push_str(&format!(
            "## The same capability in every language\n\n{}\n\n",
            catalog.cross_language(capability)
        )),
        None => out.push_str(&format!(
            "The full API reference is [on the site]({SITE}/reference/rust/{}/index.html), and \
             the copy for each published version is on [docs.rs](https://docs.rs/{krate}).\n\n",
            krate.replace('-', "_")
        )),
    }
    if !overview.is_empty() {
        out.push_str(overview);
        out.push_str("\n\n");
    }
    out.push_str(items);
    out.push_str("## License\n\nMIT - part of the [pamoja](https://github.com/molexxxx/pamoja) workspace: one memory-safe Rust core with bindings for every language.\n");
    out
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("repo root is two levels above the xtask crate")
        .to_path_buf()
}

// The workspace library crates (a `crates/<name>/src/lib.rs`), sorted; binaries like xtask
// have no lib and are skipped.
fn lib_crates() -> Result<Vec<String>, String> {
    let dir = repo_root().join("crates");
    let mut names: Vec<String> = fs::read_dir(&dir)
        .map_err(|e| format!("reading {}: {e}", dir.display()))?
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.join("src/lib.rs").is_file())
        .filter_map(|path| path.file_name().and_then(|n| n.to_str()).map(str::to_owned))
        .collect();
    names.sort();
    Ok(names)
}

// Renders every derived file as (path, contents): the per-crate READMEs, the site navigation,
// and each hand-written Markdown file that holds generated regions. Checks the capability
// map first, so a stale map fails before anything is rendered from it.
fn render_all() -> Result<Vec<(String, String)>, String> {
    let root = repo_root();
    let crates_root = root.join("crates");
    let crates = lib_crates()?;
    let catalog = Catalog::load(&root)?;
    catalog.check(&root, &crates, false)?;

    let mut files = Vec::new();
    for krate in &crates {
        let lib = fs::read_to_string(crates_root.join(krate).join("src/lib.rs"))
            .map_err(|e| format!("reading {krate}/lib.rs: {e}"))?;
        let lib_parsed =
            syn::parse_file(&lib).map_err(|e| format!("parsing {krate}/lib.rs: {e}"))?;
        let overview = doc_of(&lib_parsed.attrs);
        let items = render_items(&lib_parsed.items);
        files.push((
            format!("crates/{krate}/README.md"),
            crate_readme(krate, &catalog, &overview, &items),
        ));
    }

    files.push(("docs/SUMMARY.md".to_owned(), catalog.summary()));

    let descriptions: BTreeMap<String, String> = crates
        .iter()
        .filter_map(|krate| crate_description(krate).map(|desc| (krate.clone(), desc)))
        .collect();
    for path in region_files(&root)? {
        let text =
            fs::read_to_string(root.join(&path)).map_err(|e| format!("reading {path}: {e}"))?;
        if !regions::has_regions(&text) {
            continue;
        }
        let processed = regions::process(&text, &mut |directive| {
            if let Some(spec) = directive.strip_prefix("snippet:") {
                regions::snippet(&root, spec.trim())
            } else if let Some(table) = directive.strip_prefix("table:") {
                match table.trim() {
                    "builds" => builds::table(&root),
                    other => catalog.render(other, &descriptions),
                }
            } else {
                Err(format!("unknown directive `{directive}`"))
            }
        })
        .map_err(|e| format!("{path}: {e}"))?;
        files.push((path, processed));
    }

    files.extend(buttons::render());
    files.extend(theme::render());

    // The mark the showcase uses, carried into the site so every reference page opens with
    // it; mdBook copies anything under `docs` that is not a chapter into the built site.
    let logo = root.join("web/assets/pamoja-logo.svg");
    files.push((
        "docs/assets/pamoja-logo.svg".to_owned(),
        fs::read_to_string(&logo).map_err(|e| format!("reading {}: {e}", logo.display()))?,
    ));

    let version = version::current()?;
    files.extend(packages::render_node(&root, &catalog, &version)?);
    files.extend(packages::render_python(&root, &catalog, &version)?);
    files.extend(packages::render_dotnet(&root, &catalog)?);
    Ok(files)
}

// The hand-written Markdown files that may hold generated regions: the root README, every
// page of the site except the generated navigation, and the three binding READMEs.
fn region_files(root: &Path) -> Result<Vec<String>, String> {
    let mut paths = vec!["README.md".to_owned()];
    let mut pages = Vec::new();
    collect_markdown(&root.join("docs"), &mut pages)?;
    for page in pages {
        let relative = page
            .strip_prefix(root)
            .unwrap_or(&page)
            .to_string_lossy()
            .replace('\\', "/");
        if relative != "docs/SUMMARY.md" {
            paths.push(relative);
        }
    }
    paths.extend(
        [
            "bindings/node/README.md",
            "bindings/python/README.md",
            "bindings/dotnet/src/Pamoja.Core/README.md",
        ]
        .into_iter()
        .map(str::to_owned),
    );
    Ok(paths
        .into_iter()
        .filter(|path| root.join(path).is_file())
        .collect())
}

// Every `.md` file under `dir`, recursively, sorted.
fn collect_markdown(dir: &Path, into: &mut Vec<PathBuf>) -> Result<(), String> {
    if !dir.is_dir() {
        return Ok(());
    }
    let mut entries: Vec<PathBuf> = fs::read_dir(dir)
        .map_err(|e| format!("reading {}: {e}", dir.display()))?
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            collect_markdown(&path, into)?;
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("md") {
            into.push(path);
        }
    }
    Ok(())
}

// Renders the public items of lib.rs to Markdown, in source order.
fn render_items(items: &[Item]) -> String {
    let mut out = String::new();
    for item in items {
        match item {
            Item::Struct(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "struct",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                fields(&mut out, &item.fields);
            }
            Item::Enum(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "enum",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                for variant in &item.variants {
                    let doc = doc_of(&variant.attrs);
                    out.push_str(&format!("- `{}`", variant.ident));
                    if !doc.is_empty() {
                        out.push_str(&format!(" - {}", doc.replace('\n', " ")));
                    }
                    out.push('\n');
                }
                out.push('\n');
            }
            Item::Trait(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "trait",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                for trait_item in &item.items {
                    if let TraitItem::Fn(method) = trait_item {
                        member(
                            &mut out,
                            &tidy(method.sig.to_token_stream().to_string()),
                            &doc_of(&method.attrs),
                        );
                    }
                }
            }
            Item::Fn(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "fn",
                    &item.sig.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                code(&mut out, &tidy(item.sig.to_token_stream().to_string()));
            }
            Item::Const(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "const",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                code(
                    &mut out,
                    &tidy(format!(
                        "const {}: {}",
                        item.ident,
                        item.ty.to_token_stream()
                    )),
                );
            }
            Item::Type(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "type",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
            }
            // Inherent impls contribute their public methods under the type.
            Item::Impl(item) if item.trait_.is_none() => {
                let ty = tidy(item.self_ty.to_token_stream().to_string());
                for impl_item in &item.items {
                    if let ImplItem::Fn(method) = impl_item {
                        if is_public(&method.vis) {
                            out.push_str(&format!("### `{ty}::{}`\n\n", method.sig.ident));
                            let doc = doc_of(&method.attrs);
                            if !doc.is_empty() {
                                out.push_str(&doc);
                                out.push_str("\n\n");
                            }
                            code(&mut out, &tidy(method.sig.to_token_stream().to_string()));
                        }
                    }
                }
            }
            _ => {}
        }
    }
    out
}

fn section(out: &mut String, kind: &str, name: &str, doc: &str) {
    out.push_str(&format!("## {kind} `{name}`\n\n"));
    if !doc.is_empty() {
        out.push_str(doc);
        out.push_str("\n\n");
    }
}

fn member(out: &mut String, sig: &str, doc: &str) {
    out.push_str(&format!("### `{sig}`\n\n"));
    if !doc.is_empty() {
        out.push_str(doc);
        out.push_str("\n\n");
    }
}

fn code(out: &mut String, text: &str) {
    out.push_str(&format!("```rust\n{text}\n```\n\n"));
}

fn fields(out: &mut String, fields: &Fields) {
    if let Fields::Named(named) = fields {
        let public: Vec<_> = named.named.iter().filter(|f| is_public(&f.vis)).collect();
        if public.is_empty() {
            return;
        }
        out.push_str("Fields:\n\n");
        for field in public {
            let name = field
                .ident
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default();
            let ty = tidy(field.ty.to_token_stream().to_string());
            let doc = doc_of(&field.attrs);
            out.push_str(&format!("- `{name}: {ty}`"));
            if !doc.is_empty() {
                out.push_str(&format!(" - {}", doc.replace('\n', " ")));
            }
            out.push('\n');
        }
        out.push('\n');
    }
}

fn is_public(vis: &Visibility) -> bool {
    matches!(vis, Visibility::Public(_))
}

// Whether a rustdoc code-fence info string denotes a Rust block: empty (rustdoc's default) or
// only Rust fence attributes. An explicit other language (`text`, `toml`, `sh`) is left alone.
fn is_rust_fence(info: &str) -> bool {
    info.is_empty()
        || info.split(',').all(|token| {
            matches!(
                token.trim(),
                "rust"
                    | "no_run"
                    | "ignore"
                    | "should_panic"
                    | "compile_fail"
                    | "edition2015"
                    | "edition2018"
                    | "edition2021"
                    | "edition2024"
            )
        })
}

// The rustdoc section headers that would otherwise render as top-level Markdown headings.
const SECTIONS: &[&str] = &[
    "# Arguments",
    "# Returns",
    "# Errors",
    "# Examples",
    "# Panics",
    "# Safety",
];

// Joins an item's `///`/`//!` doc lines (dropping the single leading space rustdoc adds) and
// renders them as Markdown: rustdoc section headers become bold labels rather than H1s, and
// hidden doctest lines (`#` inside a code fence) are dropped, with `##` unescaped to `#`.
fn doc_of(attrs: &[syn::Attribute]) -> String {
    let mut raw = Vec::new();
    for attr in attrs {
        if attr.path().is_ident("doc") {
            if let syn::Meta::NameValue(nv) = &attr.meta {
                if let syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(text),
                    ..
                }) = &nv.value
                {
                    let line = text.value();
                    raw.push(line.strip_prefix(' ').unwrap_or(&line).to_owned());
                }
            }
        }
    }

    let mut out = Vec::new();
    let mut in_fence = false;
    for line in raw {
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") {
            let opening = !in_fence;
            in_fence = !in_fence;
            // rustdoc's bare (and `no_run`/`ignore`/...) fences are Rust, so tag the opening
            // fence as `rust` for highlighting; keep an explicit other language (text, toml).
            let info = trimmed.trim_start_matches('`').trim();
            if opening && is_rust_fence(info) {
                let indent = &line[..line.len() - trimmed.len()];
                out.push(format!("{indent}```rust"));
            } else {
                out.push(line);
            }
        } else if in_fence {
            if trimmed == "#" || trimmed.starts_with("# ") {
                continue; // a hidden doctest line
            }
            match trimmed.strip_prefix("##") {
                Some(rest) => out.push(format!("#{rest}")),
                None => out.push(line),
            }
        } else if SECTIONS.contains(&line.as_str()) {
            out.push(format!("**{}**", &line[2..]));
        } else if let Some(plain) = without_intra_doc_links(&line) {
            out.push(plain);
        }
    }
    out.join("\n").trim_end().to_owned()
}

// Whether a link target is a Rust path rustdoc would resolve (`Reading`, `crate::x::Y`,
// `Type::method`) rather than a URL, an anchor, or a file.
fn is_rust_path(target: &str) -> bool {
    !target.is_empty()
        && !target.contains("://")
        && !target.starts_with('#')
        && !target.contains('/')
        && !target.ends_with(".md")
        && !target.ends_with(".html")
        && target.chars().all(|c| {
            c.is_alphanumeric() || matches!(c, '_' | ':' | '<' | '>' | '!' | '(' | ')' | '@' | '.')
        })
}

// Rewrites a Markdown line so rustdoc's intra-doc links, which only docs.rs resolves, read as
// plain code: `[`Name`]` and `[text](rust::path)` become their text, a `[text][ref]` becomes
// its text, and a `[ref]: rust::path` definition line is dropped (`None`). Real links to
// URLs, anchors, and files are kept.
fn without_intra_doc_links(line: &str) -> Option<String> {
    let trimmed = line.trim_start();
    if trimmed.starts_with('[') {
        if let Some(close) = trimmed.find("]:") {
            let target = trimmed[close + 2..].trim();
            if !target.contains(' ') && is_rust_path(target) {
                return None;
            }
        }
    }

    let mut out = String::with_capacity(line.len());
    let mut rest = line;
    while let Some(open) = rest.find('[') {
        let Some(close) = rest[open..].find(']').map(|at| open + at) else {
            break;
        };
        let text = &rest[open + 1..close];
        let after = &rest[close + 1..];
        out.push_str(&rest[..open]);

        if let Some(paren) = after.strip_prefix('(') {
            if let Some(end) = paren.find(')') {
                let target = &paren[..end];
                if is_rust_path(target) {
                    out.push_str(text);
                } else {
                    out.push_str(&rest[open..close + 2 + end + 1]);
                }
                rest = &paren[end + 1..];
                continue;
            }
        }
        if let Some(bracket) = after.strip_prefix('[') {
            if let Some(end) = bracket.find(']') {
                out.push_str(text);
                rest = &bracket[end + 1..];
                continue;
            }
        }
        if text.len() >= 2 && text.starts_with('`') && text.ends_with('`') {
            out.push_str(text);
        } else {
            out.push_str(&rest[open..=close]);
        }
        rest = after;
    }
    out.push_str(rest);
    Some(out)
}

// Tidies a token-stream-rendered signature so it reads like source, not spaced tokens.
fn tidy(sig: String) -> String {
    sig.replace(" ::", "::")
        .replace(":: ", "::")
        .replace(" :", ":")
        .replace("< ", "<")
        .replace(" >", ">")
        .replace(" ,", ",")
        .replace(" (", "(")
        .replace("( ", "(")
        .replace(" )", ")")
        .replace("& ", "&")
        .replace("  ", " ")
}

// Whether a crate README on disk is hand-written (so the generator must not touch it).
fn is_handwritten(path: &Path) -> bool {
    match fs::read_to_string(path) {
        Ok(text) => !text.contains(GEN_MARKER),
        Err(_) => false,
    }
}

// Whether a generated file is a crate README that may be hand-written (no marker) and must
// then be left in place.
fn is_kept_handwritten(name: &str, path: &Path) -> bool {
    name.starts_with("crates/") && path.exists() && is_handwritten(path)
}

// Writes every derived file, leaving a hand-written crate README in place.
fn write_files(readmes: &[(String, String)]) -> bool {
    let base = repo_root();
    let mut written = 0;
    for (name, body) in readmes {
        let path = base.join(name);
        if is_kept_handwritten(name, &path) {
            continue;
        }
        if let Some(parent) = path.parent() {
            if let Err(err) = fs::create_dir_all(parent) {
                eprintln!("xtask docs: creating {}: {err}", parent.display());
                return false;
            }
        }
        if let Err(err) = fs::write(&path, body) {
            eprintln!("xtask docs: writing {}: {err}", path.display());
            return false;
        }
        written += 1;
    }
    println!(
        "docs: wrote {written} files (crate READMEs, the site navigation, and the generated regions)"
    );
    true
}

// Verifies every derived file is in sync, skipping a hand-written crate README.
fn verify_files(readmes: &[(String, String)]) -> bool {
    let base = repo_root();
    let mut stale = Vec::new();
    for (name, body) in readmes {
        let path = base.join(name);
        if is_kept_handwritten(name, &path) {
            continue;
        }
        match fs::read_to_string(&path) {
            Ok(on_disk) if &on_disk == body => {}
            _ => stale.push(name.clone()),
        }
    }
    if stale.is_empty() {
        println!(
            "docs: the crate READMEs, the site navigation, and the generated regions are in sync"
        );
        true
    } else {
        eprintln!(
            "xtask docs: stale or missing generated files: {}\n  run `cargo xtask docs` and commit the result",
            stale.join(", ")
        );
        false
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn intra_doc_links_become_plain_code() {
        assert_eq!(
            without_intra_doc_links("Use [`Reading`] with [`Codec::encode`](Codec::encode)."),
            Some("Use `Reading` with `Codec::encode`.".to_owned())
        );
        assert_eq!(
            without_intra_doc_links("see [the trait](crate::Transport) and [`X`][x]"),
            Some("see the trait and `X`".to_owned())
        );
        assert_eq!(without_intra_doc_links("[`Reading`]: crate::Reading"), None);
    }

    #[test]
    fn real_links_are_kept() {
        let kept = [
            "[RFC 4493](https://www.rfc-editor.org/rfc/rfc4493)",
            "[the section](#arguments) and [notes](../docs/notes.md)",
            "an array `[u8; 4]` in prose",
            "[LICENSE-MIT]: https://opensource.org/license/mit",
        ];
        for line in kept {
            assert_eq!(without_intra_doc_links(line).as_deref(), Some(line));
        }
    }
}
