//! One palette for every documentation site.
//!
//! The site is five generators' output stitched together: mdBook for the guides, and
//! rustdoc, typedoc, pdoc, and DocFX for the four references. Each ships its own theme, so
//! without intervention a reader crosses four visual identities in one click. No single
//! generator covers four languages well, since each understands its own type system, so
//! the fix is one palette with a thin adapter per tool, written in the variable names that
//! tool exposes. The palette is the showcase's, defined once here and emitted by
//! `cargo xtask docs`, so the sites cannot drift from each other or from the showcase.

/// The showcase's palette, which the documentation shares.
struct Palette {
    navy_0: &'static str,
    navy_1: &'static str,
    navy_2: &'static str,
    amber: &'static str,
    coral: &'static str,
    teal: &'static str,
    cream: &'static str,
    text: &'static str,
    muted: &'static str,
}

const PALETTE: Palette = Palette {
    navy_0: "#0a1322",
    navy_1: "#0e1b2e",
    navy_2: "#16263f",
    amber: "#ffb627",
    coral: "#f26a4b",
    teal: "#1fa995",
    cream: "#fbf3e4",
    text: "#e7eef8",
    muted: "#95a7be",
};

/// The showcase's typefaces, loaded from the one font host every site can reach.
const FONTS: &str = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Sora:wght@600;700;800&family=JetBrains+Mono:wght@400;500&display=swap";
const SANS: &str = "'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif";
const DISPLAY: &str = "'Sora', 'Inter', system-ui, sans-serif";
const MONO: &str = "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";

/// Render every adapter as (path, contents).
///
/// # Returns
///
/// One file per generator: mdBook's additional stylesheet, rustdoc's header fragment,
/// typedoc's custom stylesheet, pdoc's custom stylesheet, and DocFX's template stylesheet.
pub fn render() -> Vec<(String, String)> {
    vec![
        ("docs/theme/mdbook.css".to_owned(), mdbook()),
        ("docs/theme/rustdoc.html".to_owned(), rustdoc()),
        ("docs/theme/typedoc.css".to_owned(), typedoc()),
        ("docs/theme/pdoc/custom.css".to_owned(), pdoc()),
        (
            "bindings/dotnet/docs/templates/pamoja/public/main.css".to_owned(),
            docfx(),
        ),
    ]
}

// The shared header every stylesheet starts with, and the one every adapter reuses.
fn banner(tool: &str) -> String {
    format!(
        "/* Generated by `cargo xtask docs` from crates/xtask/src/theme.rs: the showcase palette in {tool}'s own variables. Edit the palette there, not this file. */\n@import url('{FONTS}');\n\n"
    )
}

// mdBook: the guides. Its navy theme is the default here, and its variables are set per
// theme class on the root element, so overriding that class wins by cascade order.
fn mdbook() -> String {
    let p = &PALETTE;
    format!(
        "{}\
.navy {{
  --bg: {navy1};
  --fg: {text};
  --sidebar-bg: {navy0};
  --sidebar-fg: {muted};
  --sidebar-active: {amber};
  --sidebar-spacer: {navy2};
  --links: {teal};
  --inline-code-color: {cream};
  --theme-popup-bg: {navy2};
  --theme-popup-border: rgba(251, 243, 228, 0.22);
  --theme-hover: {navy2};
  --quote-bg: {navy2};
  --quote-border: {amber};
  --warning-border: {coral};
  --table-border-color: rgba(251, 243, 228, 0.16);
  --table-header-bg: {navy2};
  --table-alternate-bg: {navy0};
  --searchbar-bg: {navy0};
  --searchbar-fg: {text};
  --searchbar-border-color: rgba(251, 243, 228, 0.22);
  --searchresults-header-fg: {muted};
  --searchresults-border-color: rgba(251, 243, 228, 0.16);
  --searchresults-li-bg: {navy2};
  --search-mark-bg: {amber};
  --icons: {muted};
  --icons-hover: {cream};
  --scrollbar: {navy2};
  --color-scheme: dark;
}}

html, body {{ font-family: {sans}; }}
h1, h2, h3, h4 {{ font-family: {display}; letter-spacing: -0.015em; }}
code, pre, kbd {{ font-family: {mono}; }}
.navy .hljs {{ background: {navy0}; }}
.navy a:hover {{ color: {amber}; }}
.navy .menu-title {{ font-family: {display}; font-weight: 700; color: {cream}; }}
.navy .chapter li.part-title {{ color: {amber}; font-family: {display}; letter-spacing: 0.04em; }}
.navy .chapter li a.active {{ color: {amber}; }}
.navy table thead {{ background: {navy2}; }}
",
        banner("mdBook"),
        navy0 = p.navy_0,
        navy1 = p.navy_1,
        navy2 = p.navy_2,
        amber = p.amber,
        coral = p.coral,
        teal = p.teal,
        cream = p.cream,
        text = p.text,
        muted = p.muted,
        sans = SANS,
        display = DISPLAY,
        mono = MONO,
    )
}

// rustdoc: the Rust reference. It takes a fragment for the document head, so this is a
// stylesheet link and a style block rather than a stylesheet on its own.
fn rustdoc() -> String {
    let p = &PALETTE;
    format!(
        "<!-- Generated by `cargo xtask docs` from crates/xtask/src/theme.rs: the showcase palette in rustdoc's own variables. Edit the palette there, not this file. -->
<link rel=\"stylesheet\" href=\"{FONTS}\">
<style>
:root[data-theme=\"dark\"] {{
  --main-background-color: {navy1};
  --main-color: {text};
  --link-color: {teal};
  --sidebar-background-color: {navy0};
  --code-block-background-color: {navy0};
}}
:root[data-theme=\"light\"] {{
  --link-color: {teal};
}}
body {{ font-family: {sans}; }}
h1, h2, h3, h4 {{ font-family: {display}; }}
code, pre, .code-header {{ font-family: {mono}; }}
:root[data-theme=\"dark\"] a:hover {{ color: {amber}; }}
</style>
",
        navy0 = p.navy_0,
        navy1 = p.navy_1,
        amber = p.amber,
        teal = p.teal,
        text = p.text,
        sans = SANS,
        display = DISPLAY,
        mono = MONO,
    )
}

// typedoc: the TypeScript reference. Its variables are set per colour scheme on the root
// element; the dark set is the showcase, and the light set keeps the showcase's accents.
fn typedoc() -> String {
    let p = &PALETTE;
    format!(
        "{}\
@media (prefers-color-scheme: dark) {{
  :root:not([data-theme=\"light\"]) {{
    --color-background: {navy1};
    --color-background-secondary: {navy0};
    --color-background-active: {navy2};
    --color-text: {text};
    --color-text-aside: {muted};
    --color-link: {teal};
    --color-accent: {navy2};
    --color-active-menu-item: {navy2};
    --color-focus-outline: {amber};
  }}
}}
:root[data-theme=\"dark\"] {{
  --color-background: {navy1};
  --color-background-secondary: {navy0};
  --color-background-active: {navy2};
  --color-text: {text};
  --color-text-aside: {muted};
  --color-link: {teal};
  --color-accent: {navy2};
  --color-active-menu-item: {navy2};
  --color-focus-outline: {amber};
}}
:root {{ --color-link: {teal}; --color-focus-outline: {amber}; }}
body {{ font-family: {sans}; }}
h1, h2, h3, h4, .tsd-page-title h1 {{ font-family: {display}; letter-spacing: -0.015em; }}
code, pre, .tsd-signature {{ font-family: {mono}; }}
a:hover {{ color: {amber}; }}
",
        banner("typedoc"),
        navy0 = p.navy_0,
        navy1 = p.navy_1,
        navy2 = p.navy_2,
        amber = p.amber,
        teal = p.teal,
        text = p.text,
        muted = p.muted,
        sans = SANS,
        display = DISPLAY,
        mono = MONO,
    )
}

// pdoc: the Python reference. It picks up a `custom.css` from the template directory and
// includes it after its own stylesheets, so this is a plain stylesheet like the others.
fn pdoc() -> String {
    let p = &PALETTE;
    format!(
        "{}\
:root {{ --pdoc-background: {navy1}; }}
.pdoc {{
  --text: {text};
  --muted: {muted};
  --link: {teal};
  --link-hover: {amber};
  --code: {navy0};
  --active: {navy2};
  --accent: {navy2};
  --accent2: rgba(251, 243, 228, 0.22);
  --nav-hover: {navy2};
  --name: {cream};
  --def: {teal};
  --annotation: {muted};
}}
body, .pdoc {{ font-family: {sans}; }}
.pdoc h1, .pdoc h2, .pdoc h3 {{ font-family: {display}; letter-spacing: -0.015em; }}
.pdoc code, .pdoc pre {{ font-family: {mono}; }}
",
        banner("pdoc"),
        navy0 = p.navy_0,
        navy1 = p.navy_1,
        navy2 = p.navy_2,
        amber = p.amber,
        teal = p.teal,
        cream = p.cream,
        text = p.text,
        muted = p.muted,
        sans = SANS,
        display = DISPLAY,
        mono = MONO,
    )
}

// DocFX: the C# reference. The modern template is Bootstrap, and ships `public/main.css`
// as the place a site puts its overrides; a template folder listed after `modern` layers
// this file over it.
fn docfx() -> String {
    let p = &PALETTE;
    format!(
        "{}\
[data-bs-theme=\"dark\"] {{
  --bs-body-bg: {navy1};
  --bs-body-color: {text};
  --bs-secondary-color: {muted};
  --bs-tertiary-bg: {navy0};
  --bs-secondary-bg: {navy2};
  --bs-link-color: {teal};
  --bs-link-color-rgb: 31, 169, 149;
  --bs-link-hover-color: {amber};
  --bs-link-hover-color-rgb: 255, 182, 39;
  --bs-border-color: rgba(251, 243, 228, 0.16);
  --bs-code-color: {cream};
  --bs-warning-border-subtle: {coral};
}}
:root {{
  --bs-link-color: {teal};
  --bs-link-color-rgb: 31, 169, 149;
  --bs-link-hover-color: {amber};
  --bs-link-hover-color-rgb: 255, 182, 39;
  --bs-font-sans-serif: {sans};
  --bs-font-monospace: {mono};
}}
h1, h2, h3, h4, .navbar-brand {{ font-family: {display}; letter-spacing: -0.015em; }}
.navbar-brand #logo {{ height: 30px; width: auto; margin-right: 0.35rem; }}
[data-bs-theme=\"dark\"] pre, [data-bs-theme=\"dark\"] code {{ background: {navy0}; }}
[data-bs-theme=\"dark\"] .navbar, [data-bs-theme=\"dark\"] .toc {{ background: {navy0} !important; }}
",
        banner("DocFX"),
        navy0 = p.navy_0,
        navy1 = p.navy_1,
        navy2 = p.navy_2,
        amber = p.amber,
        teal = p.teal,
        cream = p.cream,
        coral = p.coral,
        text = p.text,
        muted = p.muted,
        sans = SANS,
        display = DISPLAY,
        mono = MONO,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_adapter_carries_the_palette_and_names_its_generator() {
        for (path, body) in render() {
            assert!(body.contains(PALETTE.teal), "{path} lacks the accent");
            assert!(body.contains(PALETTE.navy_1), "{path} lacks the ground");
            assert!(
                body.contains("crates/xtask/src/theme.rs"),
                "{path} lacks its provenance"
            );
        }
    }

    #[test]
    fn the_head_fragment_is_a_fragment_and_every_stylesheet_imports_the_fonts() {
        let files = render();
        let rustdoc = &files
            .iter()
            .find(|(p, _)| p.ends_with("rustdoc.html"))
            .unwrap()
            .1;
        assert!(rustdoc.starts_with("<!--") && !rustdoc.contains("<html"));
        for (path, body) in files.iter().filter(|(p, _)| p.ends_with(".css")) {
            assert!(
                body.contains("fonts.googleapis.com"),
                "{path} lacks the typefaces"
            );
        }
    }
}
