<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Pamoja.Bus</PackageId>
    <AssemblyName>Pamoja.Bus</AssemblyName>
    <RootNamespace>Pamoja.Bus</RootNamespace>
    <Description>An in-memory typed publish and subscribe event bus.</Description>
    <PackageTags>pamoja;iot;robotics;bus</PackageTags>
    <PackageProjectUrl>https://pamoja.molex.cloud/docs/</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Pamoja.Codec/Pamoja.Codec.csproj" />
    <ProjectReference Include="../Pamoja.Core/Pamoja.Core.csproj" />
    <ProjectReference Include="../Pamoja.Native/Pamoja.Native.csproj" />
  </ItemGroup>

</Project>
