# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Ads1115Config",
    "Anomaly",
    "Bme280Calibration",
    "Bme280Measurement",
    "Calibration",
    "CanFrame",
    "CobsDecoder",
    "Debounce",
    "Depletion",
    "DeviceIdentity",
    "Ds18b20Reading",
    "Geofence",
    "J1939Message",
    "Kalman",
    "Median",
    "ModbusFrame",
    "MqttClient",
    "MqttMessage",
    "Pid",
    "Quantizer",
    "Ramp",
    "SlipDecoder",
    "Smoother",
    "SpiClock",
    "Stepper",
    "Surge",
    "Thermostat",
    "Trend",
    "Window",
    "ads1115_config_bits",
    "ads1115_config_from_bits",
    "ads1115_full_scale_microvolts",
    "ads1115_samples_per_second",
    "ads1115_to_nanovolts",
    "ads1115_to_volts",
    "bearing_between",
    "can_dlc_to_len",
    "can_fd_frame",
    "can_frame",
    "can_len_to_dlc",
    "can_remote_frame",
    "cbor_to_json_bytes",
    "cobs_decode",
    "cobs_encode",
    "cobs_max_encoded_len",
    "deadband",
    "decode_delta_samples",
    "distance_between",
    "ds18b20_celsius",
    "ds18b20_config_byte",
    "ds18b20_crc8",
    "ds18b20_max_conversion_micros",
    "ds18b20_micro_celsius",
    "ds18b20_parse_scratchpad",
    "ds18b20_resolution_bits",
    "ds18b20_step_micro_celsius",
    "encode_delta_samples",
    "fingerprint",
    "i2c_address_frame",
    "i2c_address_frame_len",
    "i2c_address_is_general_call",
    "i2c_address_is_reserved",
    "ina219_bus_millivolts",
    "ina219_calibration",
    "ina219_conversion_ready",
    "ina219_current_microamps",
    "ina219_math_overflow",
    "ina219_minimum_current_lsb_microamps",
    "ina219_power_microwatts",
    "ina219_shunt_microvolts",
    "j1939_compose",
    "j1939_decode",
    "json_to_cbor_bytes",
    "modbus_crc16",
    "modbus_parse_frame",
    "modbus_raw",
    "modbus_read_coils",
    "modbus_read_discrete_inputs",
    "modbus_read_holding_registers",
    "modbus_read_input_registers",
    "modbus_write_multiple_coils",
    "modbus_write_multiple_registers",
    "modbus_write_single_coil",
    "modbus_write_single_register",
    "pca9685_channel_register",
    "pca9685_frequency_for_prescale",
    "pca9685_limits",
    "pca9685_prescale_for_frequency",
    "pin_edge_triggered_by",
    "pin_level_from_bool",
    "pin_level_inverted",
    "pin_polarity_is_asserted",
    "pin_polarity_level",
    "pwm_duty",
    "pwm_from_counts",
    "pwm_full_off",
    "pwm_full_on",
    "pwm_servo",
    "slip_decode",
    "slip_encode",
    "slip_max_encoded_len",
    "spi_mode_clock",
    "spi_mode_from_clock",
    "stepper_step_count",
    "stepper_steps_for_degrees",
    "verify",
    "version",
    "window_capacity",
]

@typing.final
class Ads1115Config:
    r"""
    An ADS1115 configuration register, field by field.
    """
    @property
    def start_conversion(self) -> builtins.bool:
        r"""
        Whether writing this starts a single conversion.
        """
    @start_conversion.setter
    def start_conversion(self, value: builtins.bool) -> None:
        r"""
        Whether writing this starts a single conversion.
        """
    @property
    def mux(self) -> builtins.int:
        r"""
        The input multiplexer code, `0..=7`.
        """
    @mux.setter
    def mux(self, value: builtins.int) -> None:
        r"""
        The input multiplexer code, `0..=7`.
        """
    @property
    def pga(self) -> builtins.int:
        r"""
        The gain code, `0..=7`, which sets the full-scale range.
        """
    @pga.setter
    def pga(self, value: builtins.int) -> None:
        r"""
        The gain code, `0..=7`, which sets the full-scale range.
        """
    @property
    def single_shot(self) -> builtins.bool:
        r"""
        Whether to convert once per request and power down, rather than continuously.
        """
    @single_shot.setter
    def single_shot(self, value: builtins.bool) -> None:
        r"""
        Whether to convert once per request and power down, rather than continuously.
        """
    @property
    def data_rate(self) -> builtins.int:
        r"""
        The data rate code, `0..=7`.
        """
    @data_rate.setter
    def data_rate(self, value: builtins.int) -> None:
        r"""
        The data rate code, `0..=7`.
        """
    @property
    def window_comparator(self) -> builtins.bool:
        r"""
        Whether to use the window comparator rather than the traditional one.
        """
    @window_comparator.setter
    def window_comparator(self, value: builtins.bool) -> None:
        r"""
        Whether to use the window comparator rather than the traditional one.
        """
    @property
    def comparator_active_high(self) -> builtins.bool:
        r"""
        Whether the ALERT/RDY pin is active high.
        """
    @comparator_active_high.setter
    def comparator_active_high(self, value: builtins.bool) -> None:
        r"""
        Whether the ALERT/RDY pin is active high.
        """
    @property
    def comparator_latching(self) -> builtins.bool:
        r"""
        Whether the comparator latches until the conversion is read.
        """
    @comparator_latching.setter
    def comparator_latching(self, value: builtins.bool) -> None:
        r"""
        Whether the comparator latches until the conversion is read.
        """
    @property
    def comparator_queue(self) -> builtins.int:
        r"""
        The comparator queue code, `0..=3`, where `3` disables the comparator.
        """
    @comparator_queue.setter
    def comparator_queue(self, value: builtins.int) -> None:
        r"""
        The comparator queue code, `0..=3`, where `3` disables the comparator.
        """
    def __new__(cls, start_conversion: builtins.bool = True, mux: builtins.int = 0, pga: builtins.int = 2, single_shot: builtins.bool = True, data_rate: builtins.int = 4, window_comparator: builtins.bool = False, comparator_active_high: builtins.bool = False, comparator_latching: builtins.bool = False, comparator_queue: builtins.int = 3) -> Ads1115Config:
        r"""
        Builds a configuration, defaulting every field to the part's reset state.
        """
    def __eq__(self, other: Ads1115Config) -> builtins.bool:
        r"""
        Reports whether two configurations select the same settings.
        """

@typing.final
class Anomaly:
    r"""
    Flags a reading that stands out from the ones around it.
    """
    def __new__(cls, sigmas: builtins.float) -> Anomaly:
        r"""
        Creates a detector that flags a reading `sigmas` deviations from the mean.
        """
    def check(self, reading: builtins.float) -> builtins.bool:
        r"""
        Folds a reading in and reports whether it stands out.
        """

@typing.final
class Bme280Calibration:
    r"""
    A BME280's factory calibration, read once and reused for every measurement.
    """
    def __new__(cls, temp_press: typing.Sequence[builtins.int], humidity: typing.Sequence[builtins.int]) -> Bme280Calibration:
        r"""
        Builds a calibration from the bytes read out of the device's registers.
        """
    def compensate(self, measurement: typing.Sequence[builtins.int]) -> Bme280Measurement:
        r"""
        Turns an eight-byte burst read into a compensated reading.
        """

@typing.final
class Bme280Measurement:
    r"""
    A compensated BME280 reading.
    """
    @property
    def celsius(self) -> builtins.float:
        r"""
        The temperature in degrees Celsius.
        """
    @property
    def pascals(self) -> builtins.int:
        r"""
        The pressure in pascals.
        """
    @property
    def hectopascals(self) -> builtins.float:
        r"""
        The pressure in hectopascals, the unit a barometer is usually quoted in.
        """
    @property
    def relative_humidity_percent(self) -> builtins.float:
        r"""
        The relative humidity as a percentage.
        """

@typing.final
class Calibration:
    r"""
    Turns a raw sensor count into the units the reading is actually in.
    """
    @staticmethod
    def linear(scale: builtins.float, offset: builtins.float) -> Calibration:
        r"""
        Creates a calibration applying `raw * scale + offset`.
        """
    @staticmethod
    def two_point(raw_low: builtins.float, value_low: builtins.float, raw_high: builtins.float, value_high: builtins.float) -> Calibration:
        r"""
        Creates a calibration fitted through two known reference points.
        """
    def apply(self, raw: builtins.float) -> builtins.float:
        r"""
        Converts a raw reading into calibrated units.
        """

@typing.final
class CanFrame:
    r"""
    A CAN frame: an identifier, its flags, and its payload.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        The arbitration identifier, already masked to 11 or 29 bits.
        """
    @property
    def extended(self) -> builtins.bool:
        r"""
        Whether the identifier is a 29-bit extended one.
        """
    @property
    def fd(self) -> builtins.bool:
        r"""
        Whether this is a CAN-FD frame rather than classic CAN 2.0.
        """
    @property
    def remote(self) -> builtins.bool:
        r"""
        Whether this is a remote transmission request, which carries no payload.
        """
    @property
    def len(self) -> builtins.int:
        r"""
        The data length: the payload length, or the length a remote frame requests.
        """
    @property
    def dlc(self) -> builtins.int:
        r"""
        The data length code as it appears on the wire.
        """
    @property
    def data(self) -> bytes:
        r"""
        The payload, empty for a remote frame.
        """

@typing.final
class CobsDecoder:
    r"""
    Reassembles whole COBS frames from the chunks a serial port delivers.
    """
    @property
    def discarded(self) -> builtins.int:
        r"""
        How many corrupt frames this decoder has discarded.
        """
    def __new__(cls) -> CobsDecoder:
        r"""
        Creates an empty decoder, ready for the first chunk.
        """
    def feed(self, chunk: typing.Sequence[builtins.int]) -> builtins.list[bytes]:
        r"""
        Feeds a chunk of the stream and returns every frame it completed.
        """
    def reset(self) -> None:
        r"""
        Discards any partly assembled frame.
        """

@typing.final
class Debounce:
    r"""
    Stops a flickering input from acting until it has settled.
    """
    @property
    def state(self) -> builtins.bool:
        r"""
        The settled state.
        """
    def __new__(cls, samples: builtins.int, initial: builtins.bool) -> Debounce:
        r"""
        Creates a debouncer needing `samples` agreeing readings to change state.
        """
    def update(self, raw: builtins.bool) -> builtins.bool:
        r"""
        Feeds a raw reading in and returns the settled state.
        """

@typing.final
class Depletion:
    r"""
    Warns before a falling level runs out, by projecting its rate of fall.
    """
    def __new__(cls, threshold: builtins.float) -> Depletion:
        r"""
        Creates an estimator that counts down to `threshold`.
        """
    def update(self, level: builtins.float) -> typing.Optional[builtins.int]:
        r"""
        Records a level and returns the samples left before the threshold.
        
        Returns `None` while the level is steady or rising, and on the first
        reading, when no rate of fall is known yet.
        """

@typing.final
class DeviceIdentity:
    r"""
    A device's private signing identity.
    """
    @property
    def public_key(self) -> bytes:
        r"""
        The public key matching this identity, which is safe to share.
        """
    @property
    def fingerprint(self) -> builtins.str:
        r"""
        The short hex fingerprint of this identity, for logs and displays.
        """
    def __new__(cls, seed: typing.Sequence[builtins.int]) -> DeviceIdentity:
        r"""
        Creates an identity from a provisioned 32-byte secret seed.
        """
    def sign(self, payload: typing.Sequence[builtins.int]) -> bytes:
        r"""
        Signs a payload, returning the 64-byte detached signature.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Ds18b20Reading:
    r"""
    A decoded DS18B20 scratchpad.
    """
    @property
    def raw_temperature(self) -> builtins.int:
        r"""
        The raw temperature register, 1/16 degree Celsius per count.
        """
    @property
    def micro_celsius(self) -> builtins.int:
        r"""
        The temperature in micro-degrees Celsius, exact in integer arithmetic.
        """
    @property
    def celsius(self) -> builtins.float:
        r"""
        The temperature in degrees Celsius.
        """
    @property
    def alarm_high(self) -> builtins.int:
        r"""
        The high alarm threshold in whole degrees Celsius.
        """
    @property
    def alarm_low(self) -> builtins.int:
        r"""
        The low alarm threshold in whole degrees Celsius.
        """
    @property
    def resolution_bits(self) -> builtins.int:
        r"""
        The configured resolution, as a number of bits: 9, 10, 11, or 12.
        """

@typing.final
class Geofence:
    r"""
    Keeps a tracked point inside an area, and notices when it leaves.
    """
    def __new__(cls, latitude: builtins.float, longitude: builtins.float, radius_m: builtins.float) -> Geofence:
        r"""
        Creates a circular fence of `radius_m` metres around a centre fix.
        """
    def update(self, latitude: builtins.float, longitude: builtins.float) -> builtins.str:
        r"""
        Feeds a fix in and names where it sits, including a single crossing.
        
        Returns one of `"Inside"`, `"Outside"`, `"Exited"`, or `"Entered"`.
        """
    def contains(self, latitude: builtins.float, longitude: builtins.float) -> builtins.bool:
        r"""
        Reports whether a fix lies inside, without recording a crossing.
        """

@typing.final
class J1939Message:
    r"""
    The fields J1939 packs into an extended CAN identifier.
    """
    @property
    def pgn(self) -> builtins.int:
        r"""
        The parameter group number, which names what the message carries.
        """
    @property
    def priority(self) -> builtins.int:
        r"""
        The message priority, 0 (highest) to 7.
        """
    @property
    def source(self) -> builtins.int:
        r"""
        The source address: the node that sent the message.
        """
    @property
    def pdu_format(self) -> builtins.int:
        r"""
        The PDU format byte of the parameter group.
        """
    @property
    def destination(self) -> typing.Optional[builtins.int]:
        r"""
        The destination address for an addressed (PDU1) message, or `None` for a
        broadcast (PDU2) one.
        """
    @property
    def broadcast(self) -> builtins.bool:
        r"""
        Whether the message is a broadcast.
        """

@typing.final
class Kalman:
    r"""
    Estimates a true value from noisy readings, trusting the model and the sensor
    in proportion to how noisy each is.
    """
    @property
    def estimate(self) -> builtins.float:
        r"""
        The current estimate.
        """
    def __new__(cls, process_noise: builtins.float, measurement_noise: builtins.float, initial: builtins.float) -> Kalman:
        r"""
        Creates a filter from the process and measurement noise, and a first guess.
        """
    def update(self, reading: builtins.float) -> builtins.float:
        r"""
        Folds a reading in and returns the new estimate.
        """

@typing.final
class Median:
    r"""
    Rejects a single wild reading, where an average would let it pull the answer.
    """
    @property
    def value(self) -> typing.Optional[builtins.float]:
        r"""
        The current median, or ``None`` before the first reading.
        """
    def __new__(cls) -> Median:
        r"""
        Creates an empty median filter.
        """
    def update(self, reading: builtins.float) -> builtins.float:
        r"""
        Folds a reading in and returns the median of the window.
        """

@typing.final
class ModbusFrame:
    r"""
    A received Modbus RTU frame whose CRC has been verified.
    """
    @property
    def address(self) -> builtins.int:
        r"""
        The unit (slave) address the frame is addressed to or came from.
        """
    @property
    def function_code(self) -> builtins.int:
        r"""
        The function code. An exception response carries the request's code with
        its high bit set, as it appeared on the wire.
        """
    @property
    def exception(self) -> typing.Optional[builtins.int]:
        r"""
        The exception code a device reported, or `None` when the frame is not an
        exception response.
        """
    @property
    def pdu(self) -> bytes:
        r"""
        The protocol data unit: the function code and its data, without the
        address or the CRC.
        """
    def registers(self) -> builtins.list[builtins.int]:
        r"""
        Reads the 16-bit registers out of a read-registers reply.
        """
    def coils(self, count: builtins.int) -> builtins.list[builtins.bool]:
        r"""
        Reads `count` coils or discrete inputs out of a read-bits reply.
        """

@typing.final
class MqttClient:
    r"""
    An MQTT client transport backed by the native pamoja core.
    """
    def __new__(cls, *, client_id: builtins.str, host: builtins.str, port: builtins.int, keep_alive_secs: typing.Optional[builtins.int] = None, capacity: typing.Optional[builtins.int] = None, qos: typing.Optional[builtins.str] = None) -> MqttClient:
        r"""
        Creates a disconnected client from the given options.
        """
    def connect(self) -> typing.Any:
        r"""
        Connects to the broker and starts the background event loop.
        """
    def publish(self, topic: builtins.str, payload: typing.Sequence[builtins.int]) -> typing.Any:
        r"""
        Publishes a payload to a topic.
        """
    def subscribe(self, topic: builtins.str) -> typing.Any:
        r"""
        Subscribes to a topic filter.
        """
    def recv(self) -> typing.Any:
        r"""
        Awaits the next message from any subscribed topic, or `None` once the
        connection has ended.
        """
    def is_connected(self) -> typing.Any:
        r"""
        Reports whether the client currently holds an active connection.
        """
    def disconnect(self) -> typing.Any:
        r"""
        Closes the connection and stops the background event loop.
        """

@typing.final
class MqttMessage:
    r"""
    A message received from a subscribed topic.
    """
    @property
    def topic(self) -> builtins.str:
        r"""
        The topic the message was published to.
        """
    @property
    def payload(self) -> bytes:
        r"""
        The raw payload bytes.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Pid:
    r"""
    Holds a value at a setpoint by trading off present, past, and predicted error.
    """
    def __new__(cls, kp: builtins.float, ki: builtins.float, kd: builtins.float, *, min: typing.Optional[builtins.float] = None, max: typing.Optional[builtins.float] = None) -> Pid:
        r"""
        Creates a controller with the given gains, optionally clamping its output.
        """
    def update(self, setpoint: builtins.float, measurement: builtins.float, dt: builtins.float) -> builtins.float:
        r"""
        Advances the controller by one step and returns the control output.
        """
    def reset(self) -> None:
        r"""
        Clears the accumulated integral and last error.
        """

@typing.final
class Quantizer:
    r"""
    Packs float readings to a fixed precision for a metered link.
    """
    def __new__(cls, scale: builtins.float) -> Quantizer:
        r"""
        Creates a quantizer whose `scale` sets the precision kept.
        
        A scale of `100` keeps two decimal places. It must be positive and finite,
        and decoding must use the same scale the batch was encoded with.
        """
    def encode(self, readings: typing.Sequence[builtins.float]) -> bytes:
        r"""
        Quantizes and delta-encodes a batch of readings.
        """
    def decode(self, bytes: typing.Sequence[builtins.int]) -> builtins.list[builtins.float]:
        r"""
        Decodes a batch back into readings, to within the quantizer's precision.
        """

@typing.final
class Ramp:
    r"""
    Limits how fast a value may change, so a load is never slammed.
    """
    @property
    def value(self) -> builtins.float:
        r"""
        The current value.
        """
    def __new__(cls, start: builtins.float, max_step: builtins.float) -> Ramp:
        r"""
        Creates a limiter starting at `start` and moving at most `max_step` a step.
        """
    def update(self, target: builtins.float) -> builtins.float:
        r"""
        Moves one step toward `target` and returns the new value.
        """
    def set(self, value: builtins.float) -> None:
        r"""
        Forces the value without rate limiting.
        """

@typing.final
class SlipDecoder:
    r"""
    Reassembles whole SLIP frames from the chunks a serial port delivers.
    """
    @property
    def discarded(self) -> builtins.int:
        r"""
        How many corrupt frames this decoder has discarded.
        """
    def __new__(cls) -> SlipDecoder:
        r"""
        Creates an empty decoder, ready for the first chunk.
        """
    def feed(self, chunk: typing.Sequence[builtins.int]) -> builtins.list[bytes]:
        r"""
        Feeds a chunk of the stream and returns every frame it completed.
        """
    def reset(self) -> None:
        r"""
        Discards any partly assembled frame.
        """

@typing.final
class Smoother:
    r"""
    Smooths a noisy reading by weighting each new sample against the running value.
    """
    @property
    def value(self) -> typing.Optional[builtins.float]:
        r"""
        The current value, or `None` before the first sample.
        """
    def __new__(cls, weight: builtins.float) -> Smoother:
        r"""
        Creates a smoother whose `weight` sets how much each new sample counts.
        """
    def update(self, sample: builtins.float) -> builtins.float:
        r"""
        Folds a sample in and returns the smoothed value.
        """
    def reset(self) -> None:
        r"""
        Clears the smoother back to its initial state.
        """

@typing.final
class SpiClock:
    r"""
    The clock polarity and phase pair an SPI mode number names.
    """
    @property
    def cpol(self) -> builtins.bool:
        r"""
        Whether the clock idles high (CPOL = 1), which is modes 2 and 3.
        """
    @property
    def cpha(self) -> builtins.bool:
        r"""
        Whether data is sampled on the trailing edge (CPHA = 1), which is modes 1 and 3.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Renders the pair the way a datasheet quotes it.
        """

@typing.final
class Stepper:
    r"""
    A stepper motor's place in its drive sequence, and how far it has turned.
    """
    @property
    def coils(self) -> builtins.int:
        r"""
        The coil pattern currently held, without advancing.
        """
    @property
    def steps(self) -> builtins.int:
        r"""
        How many steps have been taken, signed by direction.
        """
    def __new__(cls, drive: builtins.str) -> Stepper:
        r"""
        Creates a stepper at the start of a drive pattern, with its position at zero.
        """
    def step(self, direction: builtins.str) -> builtins.int:
        r"""
        Advances one step and returns the four-bit coil pattern to apply.
        
        The most significant of the four bits is the first coil.
        """

@typing.final
class Surge:
    r"""
    Notices a step change between successive readings, such as a burst pipe.
    """
    @staticmethod
    def rising(limit: builtins.float) -> Surge:
        r"""
        Creates a detector for rises of at least `limit` between readings.
        """
    @staticmethod
    def falling(limit: builtins.float) -> Surge:
        r"""
        Creates a detector for falls of at least `limit` between readings.
        """
    def update(self, value: builtins.float) -> typing.Optional[builtins.float]:
        r"""
        Feeds a value in and returns the size of a qualifying step, or `None`.
        """

@typing.final
class Thermostat:
    r"""
    Switches a load on and off around a setpoint, with hysteresis to stop chatter.
    """
    @property
    def is_on(self) -> builtins.bool:
        r"""
        Whether the load should currently be on.
        """
    @staticmethod
    def cooling(setpoint: builtins.float, hysteresis: builtins.float) -> Thermostat:
        r"""
        Creates a cooling thermostat, which switches on when the reading rises.
        """
    @staticmethod
    def heating(setpoint: builtins.float, hysteresis: builtins.float) -> Thermostat:
        r"""
        Creates a heating thermostat, which switches on when the reading falls.
        """
    def update(self, reading: builtins.float) -> builtins.bool:
        r"""
        Feeds a reading in and returns whether the load should be on.
        """

@typing.final
class Trend:
    r"""
    Fits a line through recent readings, so a slow drift shows before it matters.
    """
    @property
    def slope(self) -> typing.Optional[builtins.float]:
        r"""
        The fitted slope in units per reading, or ``None`` without enough readings.
        """
    def __new__(cls) -> Trend:
        r"""
        Creates an empty trend estimator.
        """
    def push(self, reading: builtins.float) -> None:
        r"""
        Adds a reading.
        """

@typing.final
class Window:
    r"""
    A rolling window of the most recent readings, with the stats over them.
    """
    @property
    def capacity(self) -> builtins.int:
        r"""
        How many readings the window holds before it starts dropping.
        """
    def __new__(cls) -> Window:
        r"""
        Creates an empty window.
        """
    def push(self, reading: builtins.float) -> None:
        r"""
        Adds a reading, dropping the oldest once the window is full.
        """
    def __len__(self) -> builtins.int:
        r"""
        How many readings the window holds.
        """
    def mean(self) -> typing.Optional[builtins.float]:
        r"""
        The mean of the readings, or ``None`` while the window is empty.
        """
    def min(self) -> typing.Optional[builtins.float]:
        r"""
        The smallest reading, or ``None`` while the window is empty.
        """
    def max(self) -> typing.Optional[builtins.float]:
        r"""
        The largest reading, or ``None`` while the window is empty.
        """
    def range(self) -> typing.Optional[builtins.float]:
        r"""
        The spread between the smallest and largest readings.
        """
    def variance(self) -> typing.Optional[builtins.float]:
        r"""
        The variance of the readings, or ``None`` without enough of them.
        """

def ads1115_config_bits(config: Ads1115Config) -> builtins.int:
    r"""
    Assembles the 16-bit ADS1115 configuration register value.
    """

def ads1115_config_from_bits(bits: builtins.int) -> Ads1115Config:
    r"""
    Parses a 16-bit ADS1115 configuration register value.
    """

def ads1115_full_scale_microvolts(pga: builtins.int) -> builtins.int:
    r"""
    Returns the full-scale range an ADS1115 gain code selects, in microvolts.
    """

def ads1115_samples_per_second(data_rate: builtins.int) -> builtins.int:
    r"""
    Returns the sample rate an ADS1115 data-rate code selects.
    """

def ads1115_to_nanovolts(pga: builtins.int, raw: builtins.int) -> builtins.int:
    r"""
    Converts a raw ADS1115 conversion result to nanovolts.
    """

def ads1115_to_volts(pga: builtins.int, raw: builtins.int) -> builtins.float:
    r"""
    Converts a raw ADS1115 conversion result to volts.
    """

def bearing_between(from_latitude: builtins.float, from_longitude: builtins.float, to_latitude: builtins.float, to_longitude: builtins.float) -> builtins.float:
    r"""
    Returns the initial bearing from one coordinate to another, in degrees.
    """

def can_dlc_to_len(dlc: builtins.int) -> builtins.int:
    r"""
    Returns the payload length a data length code encodes.
    """

def can_fd_frame(id: builtins.int, extended: builtins.bool, data: typing.Sequence[builtins.int]) -> CanFrame:
    r"""
    Builds a CAN-FD frame, which carries up to 64 bytes at the discrete CAN-FD lengths.
    """

def can_frame(id: builtins.int, extended: builtins.bool, data: typing.Sequence[builtins.int]) -> CanFrame:
    r"""
    Builds a classic CAN 2.0 frame, which carries up to eight bytes.
    """

def can_len_to_dlc(len: builtins.int) -> builtins.int:
    r"""
    Returns the data length code that encodes a payload length.
    """

def can_remote_frame(id: builtins.int, extended: builtins.bool, len: builtins.int) -> CanFrame:
    r"""
    Builds a remote transmission request, which asks another node to send.
    """

def cbor_to_json_bytes(cbor: typing.Sequence[builtins.int]) -> bytes:
    r"""
    Converts a CBOR document back into its JSON encoding.
    """

def cobs_decode(frame: typing.Sequence[builtins.int]) -> bytes:
    r"""
    Reads the payload back out of a COBS frame.
    """

def cobs_encode(payload: typing.Sequence[builtins.int]) -> bytes:
    r"""
    Frames a payload as a COBS packet, terminated by its zero delimiter.
    """

def cobs_max_encoded_len(payload_len: builtins.int) -> builtins.int:
    r"""
    Returns the largest COBS frame a payload of this length can produce.
    """

def deadband(value: builtins.float, center: builtins.float, width: builtins.float) -> builtins.float:
    r"""
    Suppresses movement within `width` of `center`, so noise does not act.
    """

def decode_delta_samples(bytes: typing.Sequence[builtins.int]) -> builtins.list[builtins.int]:
    r"""
    Decodes a delta-encoded buffer back into its integer samples.
    """

def distance_between(from_latitude: builtins.float, from_longitude: builtins.float, to_latitude: builtins.float, to_longitude: builtins.float) -> builtins.float:
    r"""
    Returns the great-circle distance between two coordinates, in metres.
    """

def ds18b20_celsius(raw: builtins.int) -> builtins.float:
    r"""
    Converts a raw DS18B20 temperature register to degrees Celsius.
    """

def ds18b20_config_byte(bits: builtins.int) -> builtins.int:
    r"""
    Returns the configuration byte that selects a DS18B20 resolution.
    """

def ds18b20_crc8(data: typing.Sequence[builtins.int]) -> builtins.int:
    r"""
    Computes the Maxim CRC-8 a 1-Wire device checks its own bytes with.
    """

def ds18b20_max_conversion_micros(bits: builtins.int) -> builtins.int:
    r"""
    Returns how long a DS18B20 conversion may take at a resolution, in microseconds.
    """

def ds18b20_micro_celsius(raw: builtins.int) -> builtins.int:
    r"""
    Converts a raw DS18B20 temperature register to micro-degrees Celsius.
    """

def ds18b20_parse_scratchpad(data: typing.Sequence[builtins.int]) -> Ds18b20Reading:
    r"""
    Parses and CRC-checks a nine-byte DS18B20 scratchpad.
    """

def ds18b20_resolution_bits(config_byte: builtins.int) -> builtins.int:
    r"""
    Returns the resolution a DS18B20 configuration byte selects, in bits.
    """

def ds18b20_step_micro_celsius(bits: builtins.int) -> builtins.int:
    r"""
    Returns the temperature step a DS18B20 resolution resolves, in micro-degrees.
    """

def encode_delta_samples(samples: typing.Sequence[builtins.int]) -> bytes:
    r"""
    Delta-encodes a series of integer samples into a compact buffer.
    """

def fingerprint(public_key: typing.Sequence[builtins.int]) -> builtins.str:
    r"""
    Returns the short hex fingerprint of a public key.
    """

def i2c_address_frame(address: builtins.int, ten_bit: builtins.bool, read: builtins.bool) -> bytes:
    r"""
    Returns the address bytes a controller puts on the bus for a transfer.
    """

def i2c_address_frame_len(address: builtins.int, ten_bit: builtins.bool) -> builtins.int:
    r"""
    Returns how many bytes an address frame occupies.
    """

def i2c_address_is_general_call(address: builtins.int, ten_bit: builtins.bool) -> builtins.bool:
    r"""
    Reports whether an address is the general call address `0x00`.
    """

def i2c_address_is_reserved(address: builtins.int, ten_bit: builtins.bool) -> builtins.bool:
    r"""
    Reports whether a 7-bit address falls in a range the I2C specification reserves.
    """

def ina219_bus_millivolts(raw: builtins.int) -> builtins.int:
    r"""
    Converts a raw INA219 bus-voltage register to millivolts.
    """

def ina219_calibration(current_lsb_microamps: builtins.int, shunt_milliohms: builtins.int) -> builtins.int:
    r"""
    Computes the INA219 calibration register for a shunt and current resolution.
    """

def ina219_conversion_ready(raw: builtins.int) -> builtins.bool:
    r"""
    Reports whether an INA219 bus-voltage register says a conversion is ready.
    """

def ina219_current_microamps(raw: builtins.int, current_lsb_microamps: builtins.int) -> builtins.int:
    r"""
    Converts a raw INA219 current register to microamps.
    """

def ina219_math_overflow(raw: builtins.int) -> builtins.bool:
    r"""
    Reports whether an INA219 bus-voltage register flags a math overflow.
    """

def ina219_minimum_current_lsb_microamps(max_expected_microamps: builtins.int) -> builtins.int:
    r"""
    Returns the smallest current resolution that still covers an expected maximum.
    """

def ina219_power_microwatts(raw: builtins.int, current_lsb_microamps: builtins.int) -> builtins.int:
    r"""
    Converts a raw INA219 power register to microwatts.
    """

def ina219_shunt_microvolts(raw: builtins.int) -> builtins.int:
    r"""
    Converts a raw INA219 shunt-voltage register to microvolts.
    """

def j1939_compose(priority: builtins.int, pgn: builtins.int, source: builtins.int, destination: builtins.int) -> builtins.int:
    r"""
    Composes the extended CAN identifier a set of J1939 fields describes.
    
    The destination is used only for an addressed (PDU1) parameter group and
    ignored for a broadcast (PDU2) one.
    """

def j1939_decode(id: builtins.int, extended: builtins.bool) -> typing.Optional[J1939Message]:
    r"""
    Decodes the J1939 fields out of an extended CAN identifier.
    
    Returns `None` for a standard 11-bit identifier, which J1939 does not use.
    """

def json_to_cbor_bytes(json: typing.Sequence[builtins.int]) -> bytes:
    r"""
    Converts a JSON document into its CBOR encoding, which is typically smaller.
    """

def modbus_crc16(data: typing.Sequence[builtins.int]) -> builtins.int:
    r"""
    Computes the CRC-16/MODBUS that every RTU frame ends with.
    """

def modbus_parse_frame(data: typing.Sequence[builtins.int]) -> ModbusFrame:
    r"""
    Parses a received RTU frame, verifying its CRC.
    """

def modbus_raw(address: builtins.int, function_code: builtins.int, data: typing.Sequence[builtins.int]) -> bytes:
    r"""
    Builds a request frame from a raw function code and data.
    
    This is the escape hatch for the function codes the SDK does not name.
    """

def modbus_read_coils(address: builtins.int, start: builtins.int, count: builtins.int) -> bytes:
    r"""
    Builds a read-coils request frame (function `0x01`).
    """

def modbus_read_discrete_inputs(address: builtins.int, start: builtins.int, count: builtins.int) -> bytes:
    r"""
    Builds a read-discrete-inputs request frame (function `0x02`).
    """

def modbus_read_holding_registers(address: builtins.int, start: builtins.int, count: builtins.int) -> bytes:
    r"""
    Builds a read-holding-registers request frame (function `0x03`).
    """

def modbus_read_input_registers(address: builtins.int, start: builtins.int, count: builtins.int) -> bytes:
    r"""
    Builds a read-input-registers request frame (function `0x04`).
    """

def modbus_write_multiple_coils(address: builtins.int, start: builtins.int, values: typing.Sequence[builtins.bool]) -> bytes:
    r"""
    Builds a write-multiple-coils request frame (function `0x0F`).
    """

def modbus_write_multiple_registers(address: builtins.int, start: builtins.int, values: typing.Sequence[builtins.int]) -> bytes:
    r"""
    Builds a write-multiple-registers request frame (function `0x10`).
    """

def modbus_write_single_coil(address: builtins.int, coil: builtins.int, on: builtins.bool) -> bytes:
    r"""
    Builds a write-single-coil request frame (function `0x05`).
    """

def modbus_write_single_register(address: builtins.int, register: builtins.int, value: builtins.int) -> bytes:
    r"""
    Builds a write-single-register request frame (function `0x06`).
    """

def pca9685_channel_register(channel: builtins.int) -> builtins.int:
    r"""
    Returns the first of a PCA9685 channel's four consecutive registers.
    """

def pca9685_frequency_for_prescale(prescale: builtins.int, osc_hz: builtins.int) -> builtins.float:
    r"""
    Returns the update rate a PCA9685 prescale value produces, in hertz.
    """

def pca9685_limits() -> tuple[builtins.int, builtins.int, builtins.int]:
    r"""
    Returns the PCA9685 constants a caller sizes its arithmetic against.
    
    The tuple is the internal oscillator frequency in hertz, the channel count,
    and the counts per period.
    """

def pca9685_prescale_for_frequency(update_rate_hz: builtins.int, osc_hz: builtins.int) -> builtins.int:
    r"""
    Returns the prescale value that sets a PCA9685 update rate.
    """

def pin_edge_triggered_by(edge: builtins.str, from: builtins.str, to: builtins.str) -> builtins.bool:
    r"""
    Reports whether a change from one level to another fires an interrupt trigger.
    """

def pin_level_from_bool(high: builtins.bool) -> builtins.str:
    r"""
    Returns the level a boolean names, as `"Low"` or `"High"`.
    """

def pin_level_inverted(level: builtins.str) -> builtins.str:
    r"""
    Returns the opposite level, as `"Low"` or `"High"`.
    """

def pin_polarity_is_asserted(polarity: builtins.str, level: builtins.str) -> builtins.bool:
    r"""
    Reports whether a physical level means the signal is asserted.
    """

def pin_polarity_level(polarity: builtins.str, asserted: builtins.bool) -> builtins.str:
    r"""
    Returns the physical level that represents a logical state under a polarity.
    """

def pwm_duty(off: builtins.int) -> bytes:
    r"""
    Builds a channel's register bytes with no phase delay: on at 0, off at `off`.
    """

def pwm_from_counts(on: builtins.int, off: builtins.int) -> bytes:
    r"""
    Builds a channel's four register bytes from explicit on and off counts.
    """

def pwm_full_off() -> bytes:
    r"""
    The register bytes that hold a channel continuously low, the power-on state.
    """

def pwm_full_on() -> bytes:
    r"""
    The register bytes that hold a channel continuously high.
    """

def pwm_servo(pulse_micros: builtins.int, update_rate_hz: builtins.int) -> bytes:
    r"""
    Builds the register bytes that drive a hobby servo to a given pulse width.
    """

def slip_decode(frame: typing.Sequence[builtins.int]) -> bytes:
    r"""
    Reads the payload back out of a SLIP frame.
    """

def slip_encode(payload: typing.Sequence[builtins.int]) -> bytes:
    r"""
    Frames a payload as a SLIP packet (RFC 1055).
    """

def slip_max_encoded_len(payload_len: builtins.int) -> builtins.int:
    r"""
    Returns the largest SLIP frame a payload of this length can produce.
    """

def spi_mode_clock(mode: builtins.int) -> SpiClock:
    r"""
    Returns the `(CPOL, CPHA)` pair an SPI mode number names.
    """

def spi_mode_from_clock(cpol: builtins.bool, cpha: builtins.bool) -> builtins.int:
    r"""
    Returns the SPI mode number a `(CPOL, CPHA)` pair names.
    """

def stepper_step_count(drive: builtins.str) -> builtins.int:
    r"""
    Returns how many steps make up one electrical cycle of a drive pattern.
    """

def stepper_steps_for_degrees(degrees: builtins.float, steps_per_revolution: builtins.int) -> builtins.int:
    r"""
    Returns how many steps a rotation of `degrees` takes on a given motor.
    """

def verify(public_key: typing.Sequence[builtins.int], payload: typing.Sequence[builtins.int], signature: typing.Sequence[builtins.int]) -> builtins.bool:
    r"""
    Verifies that a signature covers a payload and was made by a public key.
    
    Returns `False` when the payload was altered or was signed by a different
    device, and raises only when an argument is the wrong length.
    """

def version() -> builtins.str:
    r"""
    Returns the version of the native pamoja module.
    """

def window_capacity() -> builtins.int:
    r"""
    The number of readings a windowed helper keeps.
    """

