//! Regenerates the cross-language conformance vectors.
//!
//! The vectors are produced here, from the Rust implementation, and committed to
//! `conformance/vectors.json`. Every binding's test suite then loads that one file
//! and asserts the same results, so a facade that drifts in any language fails
//! rather than quietly disagreeing with the others.
//!
//! Run with: `cargo run -p pamoja-examples --example conformance_vectors`

use std::fs;
use std::path::PathBuf;

use pamoja_actuators::{pca9685, stepper};
use pamoja_can::{dlc_to_len, len_to_dlc, CanId, Frame, J1939Id};
use pamoja_codec::{encode_deltas, json_to_cbor, Quantizer};
use pamoja_gpio::i2c::{Address, Direction};
use pamoja_gpio::pin::{Edge, Level, Polarity};
use pamoja_gpio::spi::Mode;
use pamoja_kit::{
    deadband, Anomaly, Boundary, Calibration, Coordinate, Depletion, Geofence, Median, Pid,
    Smoother, Thermostat, Trend, Window,
};
use pamoja_modbus::{crc16, Adu, Pdu, Response};
use pamoja_security::DeviceIdentity;
use pamoja_sensors::{ads1115, bme280, ds18b20, ina219};
use pamoja_serial::{cobs, slip};
use serde_json::{json, Value};

/// The seed every identity vector is derived from.
const SEED: [u8; 32] = [7u8; 32];

/// The payload the signature vector covers.
const PAYLOAD: &str = "21.5";

/// The document the codec vectors transcode.
const DOCUMENT: &str = r#"{"battery":88,"c":21.5,"id":"probe-1"}"#;

fn main() {
    let vectors = json!({
        "note": "Generated by `cargo run -p pamoja-examples --example conformance_vectors`. \
                 Do not edit by hand.",
        "tolerance": 1e-6,
        "identity": identity(),
        "codec": codec(),
        "smoother": smoother(),
        "pid": pid(),
        "thermostat": thermostat(),
        "depletion": depletion(),
        "calibration": calibration(),
        "deadband": deadband_vectors(),
        "geofence": geofence(),
        "serial": serial(),
        "modbus": modbus(),
        "can": can(),
        "gpio": gpio(),
        "sensors": sensors(),
        "actuators": actuators(),
        "windows": windows(),
    });

    let path = repo_root().join("conformance").join("vectors.json");
    fs::create_dir_all(path.parent().expect("conformance directory"))
        .expect("create the conformance directory");
    let mut rendered = serde_json::to_string_pretty(&vectors).expect("render the vectors");
    rendered.push('\n');
    fs::write(&path, rendered).expect("write the vectors");
    println!("wrote {}", path.display());
}

/// Signing and verifying, plus the labels derived from a public key.
fn identity() -> Value {
    let device = DeviceIdentity::from_seed(&SEED);
    let public = device.public();
    json!({
        "seed": hex(&SEED),
        "publicKey": hex(&public.to_bytes()),
        "fingerprint": public.fingerprint(),
        "payload": PAYLOAD,
        "signature": hex(&device.sign(PAYLOAD.as_bytes()).to_bytes()),
        "tamperedPayload": "21.6",
    })
}

/// Transcoding a document, and packing samples and readings for a metered link.
fn codec() -> Value {
    let samples: Vec<i64> = vec![10, 11, 13, 12, 900];
    let readings: Vec<f32> = vec![20.0, 20.1, 20.2, 20.3];
    let scale = 100.0f32;
    json!({
        "json": DOCUMENT,
        "cbor": hex(&json_to_cbor(DOCUMENT.as_bytes()).expect("transcode the document")),
        "unsortedJson": r#"{"id":"probe-1","c":21.5,"battery":88}"#,
        "deltas": {
            "samples": samples,
            "packed": hex(&encode_deltas(&samples)),
        },
        "quantizer": {
            "scale": scale,
            "readings": readings,
            "packed": hex(&Quantizer::new(scale).encode(&readings)),
            "tolerance": 1.0 / f64::from(scale),
        },
    })
}

/// Exponential smoothing over a step input.
fn smoother() -> Value {
    let weight = 0.5f32;
    let samples: Vec<f32> = vec![10.0, 20.0, 20.0, 20.0, 12.0];
    let mut smoother = Smoother::new(weight);
    let outputs: Vec<f32> = samples
        .iter()
        .map(|&sample| smoother.update(sample))
        .collect();
    json!({ "weight": weight, "samples": samples, "outputs": outputs })
}

/// A PID controller driven toward a fixed setpoint.
fn pid() -> Value {
    let (kp, ki, kd, setpoint, dt) = (1.0f32, 0.1f32, 0.05f32, 10.0f32, 0.1f32);
    let measurements: Vec<f32> = vec![0.0, 2.0, 5.0, 8.0, 9.5, 10.0];
    let mut controller = Pid::new(kp, ki, kd);
    let outputs: Vec<f32> = measurements
        .iter()
        .map(|&measurement| controller.update(setpoint, measurement, dt))
        .collect();
    json!({
        "kp": kp, "ki": ki, "kd": kd,
        "setpoint": setpoint, "dt": dt,
        "measurements": measurements,
        "outputs": outputs,
    })
}

/// On/off control with hysteresis, over a reading that crosses the band twice.
fn thermostat() -> Value {
    let (setpoint, hysteresis) = (8.0f32, 1.0f32);
    let readings: Vec<f32> = vec![7.0, 8.5, 9.5, 8.5, 7.5, 6.5];
    let mut thermostat = Thermostat::cooling(setpoint, hysteresis);
    let outputs: Vec<bool> = readings
        .iter()
        .map(|&reading| thermostat.update(reading))
        .collect();
    json!({
        "mode": "cooling",
        "setpoint": setpoint,
        "hysteresis": hysteresis,
        "readings": readings,
        "outputs": outputs,
    })
}

/// Countdown to a threshold, including the readings that produce no estimate.
fn depletion() -> Value {
    let threshold = 10.0f32;
    let levels: Vec<f32> = vec![100.0, 90.0, 80.0, 80.0, 60.0, 5.0];
    let mut depletion = Depletion::new(threshold);
    let outputs: Vec<Value> = levels
        .iter()
        .map(|&level| match depletion.update(level) {
            Some(samples) => json!(samples),
            None => Value::Null,
        })
        .collect();
    json!({ "threshold": threshold, "levels": levels, "outputs": outputs })
}

/// A two-point fit mapping raw counts onto real units.
fn calibration() -> Value {
    let (raw_low, value_low, raw_high, value_high) = (0.0f32, 0.0f32, 1024.0f32, 100.0f32);
    let calibration = Calibration::two_point(raw_low, value_low, raw_high, value_high);
    let inputs: Vec<f32> = vec![0.0, 256.0, 512.0, 1024.0];
    let outputs: Vec<f32> = inputs.iter().map(|&raw| calibration.apply(raw)).collect();
    json!({
        "rawLow": raw_low, "valueLow": value_low,
        "rawHigh": raw_high, "valueHigh": value_high,
        "inputs": inputs, "outputs": outputs,
    })
}

/// Suppressing movement inside a band around a centre value.
fn deadband_vectors() -> Value {
    let (center, width) = (0.0f32, 0.5f32);
    let inputs: Vec<f32> = vec![0.0, 0.2, -0.2, 1.0, -1.0];
    let outputs: Vec<f32> = inputs
        .iter()
        .map(|&value| deadband(value, center, width))
        .collect();
    json!({ "center": center, "width": width, "inputs": inputs, "outputs": outputs })
}

/// Fixes walked out of a fence and back, so every crossing state appears.
fn geofence() -> Value {
    let center = Coordinate::new(-1.2921, 36.8219);
    let radius_m = 50.0;
    let fixes = [
        (-1.2921, 36.8219),
        (-1.2930, 36.8219),
        (-1.2935, 36.8219),
        (-1.2921, 36.8219),
    ];
    let mut fence = Geofence::new(center, radius_m);
    let boundaries: Vec<&str> = fixes
        .iter()
        .map(|&(latitude, longitude)| name(fence.update(Coordinate::new(latitude, longitude))))
        .collect();
    json!({
        "center": { "latitude": center.latitude, "longitude": center.longitude },
        "radiusM": radius_m,
        "fixes": fixes
            .iter()
            .map(|&(latitude, longitude)| json!({ "latitude": latitude, "longitude": longitude }))
            .collect::<Vec<Value>>(),
        "boundaries": boundaries,
    })
}

/// Both serial framings over a payload full of bytes each one has to escape, plus
/// a stream carrying a corrupt frame between two good ones.
fn serial() -> Value {
    // Every byte here is special to one framing or the other: the SLIP delimiter
    // and escape, and the zero COBS removes.
    let payload = [0xC0u8, 0xDB, 0x00, 0x2A];
    let mut framed = [0u8; 64];

    let slip_len = slip::encode(&payload, &mut framed).expect("frame the payload");
    let slip_frame = framed[..slip_len].to_vec();
    let cobs_len = cobs::encode(&payload, &mut framed).expect("frame the payload");
    let cobs_frame = framed[..cobs_len].to_vec();

    // A good frame, an escape truncated by the delimiter, then a good frame. The
    // corrupt one must be dropped without taking its neighbours with it.
    let stream = [b'o', b'k', 0xC0, 0xDB, 0xC0, b'g', b'o', 0xC0];
    let mut decoder: slip::SlipDecoder<64> = slip::SlipDecoder::new();
    let mut frames: Vec<String> = Vec::new();
    let mut discarded = 0u32;
    for &byte in &stream {
        match decoder.push(byte) {
            Ok(Some(frame)) => frames.push(hex(frame)),
            Ok(None) => {}
            Err(_) => discarded += 1,
        }
    }

    let cobs_stream = [0x03u8, 0x11, 0x22, 0x02, 0x33, 0x00];
    let mut cobs_decoder: cobs::CobsDecoder<64> = cobs::CobsDecoder::new();
    let mut cobs_frames: Vec<String> = Vec::new();
    for &byte in &cobs_stream {
        if let Ok(Some(frame)) = cobs_decoder.push(byte) {
            cobs_frames.push(hex(frame));
        }
    }

    json!({
        "payload": hex(&payload),
        "slipFrame": hex(&slip_frame),
        "cobsFrame": hex(&cobs_frame),
        "slipMaxEncodedLen": slip::max_encoded_len(payload.len()),
        "cobsMaxEncodedLen": cobs::max_encoded_len(payload.len()),
        "corruptSlipFrame": hex(&[0xDB, 0x01, 0xC0]),
        "slipStream": {
            "bytes": hex(&stream),
            "chunk": 3,
            "frames": frames,
            "discarded": discarded,
        },
        "cobsStream": {
            "bytes": hex(&cobs_stream),
            "chunk": 4,
            "frames": cobs_frames,
        },
    })
}

/// Modbus request frames, the replies they draw, and a frame corrupted on the wire.
fn modbus() -> Value {
    let read = Pdu::read_holding_registers(0x006B, 3).to_adu(0x11);

    // The reply the specification's own worked example gives for that request.
    let reply = Adu::from_pdu(0x11, &[0x03, 0x06, 0x02, 0x2B, 0x00, 0x00, 0x00, 0x64])
        .expect("assemble the reply");
    let registers: Vec<u16> = Response::new(reply.pdu())
        .registers()
        .expect("read the registers")
        .collect();

    // A read-coils reply carrying four bits packed least-significant first.
    let bit_reply = Adu::from_pdu(0x11, &[0x01, 0x01, 0b0000_1101]).expect("assemble the reply");
    let coils: Vec<bool> = Response::new(bit_reply.pdu())
        .coils(4)
        .expect("read the coils")
        .collect();

    // Registers above 0x7FFF, which catch a binding that reads them as signed.
    let high =
        Adu::from_pdu(0x11, &[0x03, 0x04, 0xFF, 0xFF, 0x80, 0x00]).expect("assemble the reply");
    let high_registers: Vec<u16> = Response::new(high.pdu())
        .registers()
        .expect("read the registers")
        .collect();

    let refused = Adu::from_pdu(0x11, &[0x83, 0x02]).expect("assemble the reply");

    let mut corrupt = read.as_bytes().to_vec();
    corrupt[2] ^= 0xFF;
    let checked = &read.as_bytes()[..read.as_bytes().len() - 2];

    json!({
        "readHoldingRegisters": {
            "address": 0x11, "start": 0x006B, "count": 3,
            "frame": hex(read.as_bytes()),
        },
        "readCoils": {
            "address": 0x11, "start": 0x0013, "count": 37,
            "frame": hex(Pdu::read_coils(0x0013, 37).to_adu(0x11).as_bytes()),
        },
        "writeSingleRegister": {
            "address": 0x11, "register": 0x0001, "value": 0x0003,
            "frame": hex(Pdu::write_single_register(0x0001, 0x0003).to_adu(0x11).as_bytes()),
        },
        "writeMultipleRegisters": {
            "address": 0x11, "start": 0x0001, "values": [0x000A, 0x0102],
            "frame": hex(
                Pdu::write_multiple_registers(0x0001, &[0x000A, 0x0102])
                    .expect("build the request")
                    .to_adu(0x11)
                    .as_bytes(),
            ),
        },
        "writeMultipleCoils": {
            "address": 0x11, "start": 0x0013, "values": [true, false, true, true, false],
            "frame": hex(
                Pdu::write_multiple_coils(0x0013, &[true, false, true, true, false])
                    .expect("build the request")
                    .to_adu(0x11)
                    .as_bytes(),
            ),
        },
        "reply": {
            "frame": hex(reply.as_bytes()),
            "address": reply.address(),
            "functionCode": reply.function_code(),
            "pdu": hex(reply.pdu()),
            "registers": registers,
        },
        "highRegisterReply": {
            "frame": hex(high.as_bytes()),
            "registers": high_registers,
        },
        "bitReply": {
            "frame": hex(bit_reply.as_bytes()),
            "count": 4,
            "coils": coils,
        },
        "exceptionReply": {
            "frame": hex(refused.as_bytes()),
            "functionCode": refused.function_code(),
            "exception": refused.exception().map(pamoja_modbus::Exception::code),
        },
        "corruptFrame": hex(&corrupt),
        "crc": { "data": hex(checked), "value": crc16(checked) },
    })
}

/// CAN frames of each kind, the CAN-FD length table, and J1939 identifiers.
fn can() -> Value {
    let classic = Frame::new(CanId::standard(0x20A), &[0x01, 0xF4]).expect("build the frame");
    let fd = Frame::fd(CanId::extended(0x1234_5678), &[0xAB; 32]).expect("build the frame");
    let remote = Frame::remote(CanId::standard(0x20A), 4);

    let lengths: Vec<Value> = [0usize, 1, 8, 12, 16, 20, 24, 32, 48, 64]
        .iter()
        .map(|&len| json!({ "len": len, "dlc": len_to_dlc(len) }))
        .collect();
    let codes: Vec<Value> = (0u8..16)
        .map(|dlc| json!({ "dlc": dlc, "len": dlc_to_len(dlc) }))
        .collect();

    json!({
        "classic": {
            "id": 0x20A, "extended": false, "data": hex(classic.data()),
            "dlc": classic.dlc(), "len": classic.len(),
        },
        "fd": {
            "id": 0x1234_5678u32, "extended": true, "data": hex(fd.data()),
            "dlc": fd.dlc(), "len": fd.len(),
        },
        "remote": {
            "id": 0x20A, "extended": false, "requested": 4,
            "dlc": remote.dlc(), "len": remote.len(), "dataLen": remote.data().len(),
        },
        "tooLongForClassic": 9,
        "invalidFdLength": 13,
        "lengths": lengths,
        "codes": codes,
        "j1939": [
            // Electronic engine controller 1, a PDU2 broadcast every genset sends.
            j1939(0x0CF0_0400),
            // A request PGN, which is PDU1 and so names a destination.
            j1939(J1939Id::from_parts(6, 0x0EA00, 0x21, 0x0A).to_id().raw()),
        ],
        "standardIsNotJ1939": 0x123,
    })
}

/// One J1939 identifier decoded into the fields every binding reports.
fn j1939(raw: u32) -> Value {
    let message = J1939Id::from_id(CanId::extended(raw)).expect("decode the identifier");
    json!({
        "id": raw,
        "pgn": message.pgn(),
        "priority": message.priority(),
        "source": message.source(),
        "pduFormat": message.pdu_format(),
        "destination": message.destination(),
        "broadcast": message.is_broadcast(),
    })
}

/// I2C address frames, the SPI mode table, and the pin logic around them.
fn gpio() -> Value {
    let addresses: Vec<Value> = [
        (0x76u16, false),
        (0x68, false),
        (0x00, false),
        (0x07, false),
        (0x08, false),
        (0x77, false),
        (0x78, false),
        (0x2A5, true),
    ]
    .iter()
    .map(|&(value, ten_bit)| {
        let address = if ten_bit {
            Address::ten_bit(value).expect("validate the address")
        } else {
            Address::seven_bit(value as u8).expect("validate the address")
        };
        let mut write = [0u8; 2];
        let mut read = [0u8; 2];
        let written = address
            .write_frame(Direction::Write, &mut write)
            .expect("frame the address");
        let readable = address
            .write_frame(Direction::Read, &mut read)
            .expect("frame the address");
        json!({
            "address": value,
            "tenBit": ten_bit,
            "writeFrame": hex(&write[..written]),
            "readFrame": hex(&read[..readable]),
            "frameLen": address.frame_len(),
            "reserved": address.is_reserved(),
            "generalCall": address.is_general_call(),
        })
    })
    .collect();

    let modes: Vec<Value> = [Mode::Mode0, Mode::Mode1, Mode::Mode2, Mode::Mode3]
        .iter()
        .map(|&mode| {
            let (cpol, cpha) = mode.cpol_cpha();
            json!({ "mode": mode.number(), "cpol": cpol, "cpha": cpha })
        })
        .collect();

    let transitions = [
        (Level::Low, Level::High),
        (Level::High, Level::Low),
        (Level::High, Level::High),
    ];
    let edges: Vec<Value> = [Edge::Rising, Edge::Falling, Edge::Both]
        .iter()
        .flat_map(|&edge| {
            transitions.iter().map(move |&(from, to)| {
                json!({
                    "edge": edge_name(edge),
                    "from": level_name(from),
                    "to": level_name(to),
                    "triggered": edge.triggered_by(from, to),
                })
            })
        })
        .collect();

    let polarities: Vec<Value> = [Polarity::ActiveHigh, Polarity::ActiveLow]
        .iter()
        .flat_map(|&polarity| {
            [true, false].iter().map(move |&asserted| {
                let level = polarity.level(asserted);
                json!({
                    "polarity": polarity_name(polarity),
                    "asserted": asserted,
                    "level": level_name(level),
                    "isAsserted": polarity.is_asserted(level),
                })
            })
        })
        .collect();

    json!({
        "i2c": addresses,
        "outOfRangeSevenBit": 0x80,
        "outOfRangeTenBit": 0x400,
        "spi": modes,
        "invalidSpiMode": 4,
        "edges": edges,
        "polarities": polarities,
    })
}

/// Names a level, matching the spelling every binding exposes.
fn level_name(level: Level) -> &'static str {
    match level {
        Level::Low => "Low",
        Level::High => "High",
    }
}

/// Names an interrupt edge, matching the spelling every binding exposes.
fn edge_name(edge: Edge) -> &'static str {
    match edge {
        Edge::Rising => "Rising",
        Edge::Falling => "Falling",
        Edge::Both => "Both",
    }
}

/// Names a polarity, matching the spelling every binding exposes.
fn polarity_name(polarity: Polarity) -> &'static str {
    match polarity {
        Polarity::ActiveHigh => "ActiveHigh",
        Polarity::ActiveLow => "ActiveLow",
    }
}

/// The sensor decoders, over register bytes taken from the parts' own datasheets.
fn sensors() -> Value {
    // The compensation coefficients from the Bosch BME280 datasheet's worked
    // example, laid out in the register order a burst read returns them in.
    let mut temp_press = [0u8; 26];
    temp_press[0..2].copy_from_slice(&27_504u16.to_le_bytes());
    temp_press[2..4].copy_from_slice(&26_435i16.to_le_bytes());
    temp_press[4..6].copy_from_slice(&(-1_000i16).to_le_bytes());
    temp_press[6..8].copy_from_slice(&36_477u16.to_le_bytes());
    temp_press[8..10].copy_from_slice(&(-10_685i16).to_le_bytes());
    temp_press[10..12].copy_from_slice(&3_024i16.to_le_bytes());
    temp_press[12..14].copy_from_slice(&2_855i16.to_le_bytes());
    temp_press[14..16].copy_from_slice(&140i16.to_le_bytes());
    temp_press[16..18].copy_from_slice(&(-7i16).to_le_bytes());
    temp_press[18..20].copy_from_slice(&15_500i16.to_le_bytes());
    temp_press[20..22].copy_from_slice(&(-14_600i16).to_le_bytes());
    temp_press[22..24].copy_from_slice(&6_000i16.to_le_bytes());
    temp_press[25] = 75;
    let humidity = [0x64u8, 0x01, 0x00, 0x14, 0x2D, 0x03, 0x1E];

    // The data registers, carrying the datasheet's raw temperature and pressure.
    let measurement = [0x65, 0x5A, 0xC0, 0x7E, 0xED, 0x00, 0x7F, 0xFF];
    let calibration = bme280::Calibration::from_registers(&temp_press, &humidity);
    let reading = calibration.compensate(&bme280::RawMeasurement::from_registers(&measurement));

    // A DS18B20 reporting 25.0625 C at 12-bit resolution, CRC included.
    let mut scratchpad = [0x91u8, 0x01, 0x4B, 0x46, 0x7F, 0xFF, 0x0C, 0x10, 0x00];
    scratchpad[8] = ds18b20::crc8(&scratchpad[..8]);
    let mut corrupt = scratchpad;
    corrupt[0] ^= 0xFF;
    let decoded = ds18b20::Scratchpad::parse(&scratchpad).expect("parse the scratchpad");

    let resolutions: Vec<Value> = [9u8, 10, 11, 12]
        .iter()
        .map(|&bits| {
            let resolution = match bits {
                9 => ds18b20::Resolution::Bits9,
                10 => ds18b20::Resolution::Bits10,
                11 => ds18b20::Resolution::Bits11,
                _ => ds18b20::Resolution::Bits12,
            };
            json!({
                "bits": bits,
                "configByte": resolution.config_byte(),
                "stepMicroCelsius": resolution.step_micro_celsius(),
                "maxConversionMicros": resolution.max_conversion_micros(),
            })
        })
        .collect();

    // The INA219 datasheet's design example: 15 A across a 2 milliohm shunt.
    const CURRENT_LSB: u32 = 1_000;

    let gains: Vec<Value> = (0u8..8)
        .map(|code| {
            json!({
                "pga": code,
                "fullScaleMicrovolts": ads1115::Pga::from_code(code).full_scale_microvolts(),
                "nanovoltsAtFullScale": ads1115::to_nanovolts(ads1115::Pga::from_code(code), 32_767),
            })
        })
        .collect();
    let rates: Vec<Value> = (0u8..8)
        .map(|code| {
            json!({
                "dataRate": code,
                "samplesPerSecond": ads1115::DataRate::from_code(code).samples_per_second(),
            })
        })
        .collect();
    let reset = ads1115::Config::from_bits(ads1115::CONFIG_RESET);

    json!({
        "bme280": {
            "calibrationTempPress": hex(&temp_press),
            "calibrationHumidity": hex(&humidity),
            "measurement": hex(&measurement),
            "celsius": reading.celsius(),
            "pascals": reading.pascals(),
            "hectopascals": reading.hectopascals(),
            "relativeHumidityPercent": reading.relative_humidity_percent(),
        },
        "ds18b20": {
            "scratchpad": hex(&scratchpad),
            "corruptScratchpad": hex(&corrupt),
            "rawTemperature": decoded.raw_temperature(),
            "microCelsius": decoded.temperature_micro_celsius(),
            "celsius": decoded.temperature_celsius(),
            "alarmHigh": decoded.alarm_high(),
            "alarmLow": decoded.alarm_low(),
            "resolutionBits": decoded.resolution().bits(),
            "resolutions": resolutions,
            "invalidResolution": 8,
            "crcData": hex(&scratchpad[..8]),
            "crc": ds18b20::crc8(&scratchpad[..8]),
        },
        "ina219": {
            "currentLsbMicroamps": CURRENT_LSB,
            "shuntMilliohms": 2,
            "calibration": ina219::calibration(CURRENT_LSB, 2),
            "maxExpectedMicroamps": 15_000_000u32,
            "minimumCurrentLsbMicroamps": ina219::minimum_current_lsb_microamps(15_000_000),
            "rawShunt": 1_000,
            "shuntMicrovolts": ina219::shunt_microvolts(1_000),
            "rawBus": 0x1F40u16,
            "busMillivolts": ina219::bus_millivolts(0x1F40),
            "conversionReady": ina219::conversion_ready(0x0002),
            "mathOverflow": ina219::math_overflow(0x0001),
            "rawCurrent": 1_000,
            "currentMicroamps": ina219::current_microamps(1_000, CURRENT_LSB),
            "rawPower": 100u16,
            "powerMicrowatts": ina219::power_microwatts(100, CURRENT_LSB),
        },
        "ads1115": {
            "configReset": ads1115::CONFIG_RESET,
            "resetConfig": {
                "startConversion": reset.start_conversion,
                "mux": reset.mux.code(),
                "pga": reset.pga.code(),
                "singleShot": matches!(reset.mode, ads1115::Mode::SingleShot),
                "dataRate": reset.data_rate.code(),
                "windowComparator": matches!(reset.comparator_mode, ads1115::ComparatorMode::Window),
                "comparatorActiveHigh": matches!(
                    reset.comparator_polarity,
                    ads1115::ComparatorPolarity::ActiveHigh
                ),
                "comparatorLatching": matches!(
                    reset.comparator_latch,
                    ads1115::ComparatorLatch::Latching
                ),
                "comparatorQueue": reset.comparator_queue.code(),
            },
            "gains": gains,
            "rates": rates,
        },
    })
}

/// The actuator encoders, and the coil patterns a stepper walks.
fn actuators() -> Value {
    let cycle: Vec<u8> = {
        let mut sequencer = stepper::Sequencer::new(stepper::Drive::HalfStep);
        let mut patterns = vec![sequencer.coils()];
        for _ in 0..stepper::Drive::HalfStep.step_count() {
            patterns.push(sequencer.step(stepper::Direction::Forward));
        }
        patterns
    };

    json!({
        "pca9685": {
            "internalOscHz": pca9685::INTERNAL_OSC_HZ,
            "channels": pca9685::CHANNELS,
            "counts": pca9685::COUNTS,
            "channelRegisters": (0..pca9685::CHANNELS)
                .map(|channel| json!({
                    "channel": channel,
                    "register": pca9685::channel_register(channel),
                }))
                .collect::<Vec<Value>>(),
            "invalidChannel": pca9685::CHANNELS,
            "updateRateHz": 50,
            "prescale": pca9685::prescale_for_frequency(50, pca9685::INTERNAL_OSC_HZ),
            "frequencyForPrescale": pca9685::frequency_for_prescale(
                pca9685::prescale_for_frequency(50, pca9685::INTERNAL_OSC_HZ),
                pca9685::INTERNAL_OSC_HZ,
            ),
        },
        "pwm": {
            "duty": { "off": 2048, "bytes": hex(&pca9685::Pwm::duty(2048).bytes()) },
            "servoCentre": {
                "pulseMicros": 1_500,
                "updateRateHz": 50,
                "bytes": hex(&pca9685::Pwm::servo(1_500, 50).bytes()),
            },
            "fullOn": hex(&pca9685::Pwm::full_on().bytes()),
            "fullOff": hex(&pca9685::Pwm::full_off().bytes()),
        },
        "stepper": {
            "drive": "HalfStep",
            "stepCount": stepper::Drive::HalfStep.step_count(),
            "forwardCycle": cycle,
            "waveStepCount": stepper::Drive::Wave.step_count(),
            "fullStepCount": stepper::Drive::FullStep.step_count(),
            "degrees": 90.0,
            "stepsPerRevolution": 200,
            "stepsForDegrees": stepper::steps_for_degrees(90.0, 200),
        },
    })
}

/// The windowed helpers, at the fixed capacity every binding builds them with.
fn windows() -> Value {
    let readings: Vec<f32> = vec![10.0, 20.0, 30.0, 20.0, 900.0, 20.0];

    let mut window: Window<32> = Window::new();
    let mut window_states: Vec<Value> = Vec::new();
    for &reading in &readings {
        window.push(reading);
        window_states.push(json!({
            "len": window.len(),
            "mean": window.mean(),
            "min": window.min(),
            "max": window.max(),
            "range": window.range(),
        }));
    }

    let mut median: Median<32> = Median::new();
    let medians: Vec<f32> = readings
        .iter()
        .map(|&reading| median.update(reading))
        .collect();

    let rising: Vec<f32> = vec![1.0, 2.0, 3.0, 4.0];
    let mut trend: Trend<32> = Trend::new();
    let slopes: Vec<Value> = rising
        .iter()
        .map(|&reading| {
            trend.push(reading);
            match trend.slope() {
                Some(slope) => json!(slope),
                None => Value::Null,
            }
        })
        .collect();

    let steady: Vec<f32> = vec![20.0, 20.1, 19.9, 20.0, 20.2, 19.8, 20.1, 20.0];
    let mut anomaly: Anomaly<32> = Anomaly::new(3.0);
    let flags: Vec<bool> = steady
        .iter()
        .chain(core::iter::once(&900.0))
        .map(|&reading| anomaly.check(reading))
        .collect();

    json!({
        "capacity": 32,
        "window": { "readings": readings, "states": window_states },
        "median": { "readings": readings, "outputs": medians },
        "trend": { "readings": rising, "slopes": slopes },
        "anomaly": {
            "sigmas": 3.0,
            "readings": steady.iter().chain(core::iter::once(&900.0)).collect::<Vec<&f32>>(),
            "flags": flags,
        },
    })
}

/// Names a boundary state, matching the spelling every binding exposes.
fn name(boundary: Boundary) -> &'static str {
    match boundary {
        Boundary::Inside => "Inside",
        Boundary::Outside => "Outside",
        Boundary::Exited => "Exited",
        Boundary::Entered => "Entered",
    }
}

/// Renders bytes as lowercase hex, the form every binding can parse.
fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

/// Locates the repository root from this crate's manifest directory.
fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the examples crate sits under the repository root")
        .to_path_buf()
}
