// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (process.report && typeof process.report.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./pamoja-native.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-android-arm64')
        const bindingPackageVersion = require('@pamoja/native-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./pamoja-native.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-android-arm-eabi')
        const bindingPackageVersion = require('@pamoja/native-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if ((process.config && process.config.variables && process.config.variables.shlib_suffix === 'dll.a') || (process.config && process.config.variables && process.config.variables.node_target_type === 'shared_library')) {
        try {
        return require('./pamoja-native.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-win32-x64-gnu')
        const bindingPackageVersion = require('@pamoja/native-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./pamoja-native.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-win32-x64-msvc')
        const bindingPackageVersion = require('@pamoja/native-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./pamoja-native.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-win32-ia32-msvc')
        const bindingPackageVersion = require('@pamoja/native-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./pamoja-native.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-win32-arm64-msvc')
        const bindingPackageVersion = require('@pamoja/native-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./pamoja-native.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@pamoja/native-darwin-universal')
      const bindingPackageVersion = require('@pamoja/native-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./pamoja-native.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-darwin-x64')
        const bindingPackageVersion = require('@pamoja/native-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./pamoja-native.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-darwin-arm64')
        const bindingPackageVersion = require('@pamoja/native-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./pamoja-native.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-freebsd-x64')
        const bindingPackageVersion = require('@pamoja/native-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./pamoja-native.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-freebsd-arm64')
        const bindingPackageVersion = require('@pamoja/native-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./pamoja-native.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pamoja/native-linux-x64-musl')
          const bindingPackageVersion = require('@pamoja/native-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./pamoja-native.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pamoja/native-linux-x64-gnu')
          const bindingPackageVersion = require('@pamoja/native-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./pamoja-native.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pamoja/native-linux-arm64-musl')
          const bindingPackageVersion = require('@pamoja/native-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./pamoja-native.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pamoja/native-linux-arm64-gnu')
          const bindingPackageVersion = require('@pamoja/native-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./pamoja-native.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pamoja/native-linux-arm-musleabihf')
          const bindingPackageVersion = require('@pamoja/native-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./pamoja-native.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pamoja/native-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@pamoja/native-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./pamoja-native.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pamoja/native-linux-loong64-musl')
          const bindingPackageVersion = require('@pamoja/native-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./pamoja-native.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pamoja/native-linux-loong64-gnu')
          const bindingPackageVersion = require('@pamoja/native-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./pamoja-native.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pamoja/native-linux-riscv64-musl')
          const bindingPackageVersion = require('@pamoja/native-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./pamoja-native.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@pamoja/native-linux-riscv64-gnu')
          const bindingPackageVersion = require('@pamoja/native-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./pamoja-native.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-linux-ppc64-gnu')
        const bindingPackageVersion = require('@pamoja/native-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./pamoja-native.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-linux-s390x-gnu')
        const bindingPackageVersion = require('@pamoja/native-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./pamoja-native.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-openharmony-arm64')
        const bindingPackageVersion = require('@pamoja/native-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./pamoja-native.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-openharmony-x64')
        const bindingPackageVersion = require('@pamoja/native-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./pamoja-native.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@pamoja/native-openharmony-arm')
        const bindingPackageVersion = require('@pamoja/native-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.1.18' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

function createLoadErrorChain(errors) {
  return errors.reduce((previous, current) => {
    let message
    try {
      message =
        current && typeof current.message === 'string'
          ? current.message
          : String(current)
    } catch {
      message = 'Unknown error'
    }
    const error = new Error(message)
    error.cause = previous
    return error
  }, null)
}

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → prefer WASI, but retain native as a lazy fallback
//   'error'                  → require WASI without initializing a native fallback
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
//
// NAPI_RS_WASI_FLAVOR selects one exact generated flavor and implies strict
// WASI loading. It never crosses into another flavor or falls back to native.
const __napiWasiFlavors = ["wasm32-wasi"]
const __napiWasiFlavor = process.env.NAPI_RS_WASI_FLAVOR
const __napiWasiFlavorRequested =
  typeof __napiWasiFlavor === 'string' && __napiWasiFlavor.length > 0
if (
  __napiWasiFlavorRequested &&
  __napiWasiFlavors.indexOf(__napiWasiFlavor) === -1
) {
  throw new Error(
    'Unsupported WASI flavor "' +
      __napiWasiFlavor +
      '". Available flavors: ' +
      __napiWasiFlavors.join(', '),
  )
}
const forceWasiError = process.env.NAPI_RS_FORCE_WASI === 'error'
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' ||
  forceWasiError ||
  __napiWasiFlavorRequested

if (!forceWasi) {
  nativeBinding = requireNative()
}

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingLoaded = false
  const wasiBindingErrors = []
  const __napiWasiResolveCandidate = (specifier, isPackage, localArtifacts) => {
    try {
      require.resolve(specifier)
    } catch (resolveError) {
      if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
        throw resolveError
      }
      if (isPackage) {
        try {
          require.resolve(specifier + '/package.json')
        } catch (packageError) {
          if (packageError && packageError.code === 'MODULE_NOT_FOUND') {
            return resolveError
          }
          // An exports restriction proves the package exists even when its
          // package.json is not public. Preserve the root resolution failure.
          throw resolveError
        }
        // The package exists but its main/export target is broken.
        throw resolveError
      }
      return resolveError
    }
    if (localArtifacts) {
      let artifactError = null
      for (let i = 0; i < localArtifacts.length; i++) {
        try {
          require.resolve(localArtifacts[i])
          return null
        } catch (resolveError) {
          if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
            throw resolveError
          }
          artifactError = resolveError
        }
      }
      return artifactError
    }
    return null
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === "wasm32-wasi")) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('./pamoja-native.wasi.cjs', false, ["./pamoja-native.wasm32-wasi.debug.wasm","./pamoja-native.wasm32-wasi.wasm"])
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        wasiBinding = require('./pamoja-native.wasi.cjs')
        nativeBinding = wasiBinding
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === "wasm32-wasi")) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('@pamoja/native-wasm32-wasi', true, undefined)
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        if (process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          const bindingPackageVersion = require('@pamoja/native-wasm32-wasi/package.json').version
          if (bindingPackageVersion !== '0.1.18') {
            throw new Error(`WASI binding package version mismatch, expected 0.1.18 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
        }
        wasiBinding = require('@pamoja/native-wasm32-wasi')
        nativeBinding = wasiBinding
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (
    !wasiBindingLoaded &&
    forceWasi &&
    !forceWasiError &&
    !__napiWasiFlavorRequested
  ) {
    nativeBinding = requireNative()
  }
  if ((forceWasiError || __napiWasiFlavorRequested) && !wasiBindingLoaded) {
    const error = new Error(
      __napiWasiFlavorRequested
        ? 'WASI binding for flavor "' + __napiWasiFlavor + '" not found'
        : 'WASI binding not found and NAPI_RS_FORCE_WASI is set to error',
    )
    error.cause = createLoadErrorChain(wasiBindingErrors)
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
    )
    // assign instead of the `new Error(message, { cause })` options form,
    // which Node < 16.9 silently ignores
    error.cause = createLoadErrorChain(loadErrors)
    throw error
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.AgreementKey = nativeBinding.AgreementKey
module.exports.Anomaly = nativeBinding.Anomaly
module.exports.AuditEntry = nativeBinding.AuditEntry
module.exports.AuditLog = nativeBinding.AuditLog
module.exports.AuditVerifier = nativeBinding.AuditVerifier
module.exports.Bme280Calibration = nativeBinding.Bme280Calibration
module.exports.Bmp280Calibration = nativeBinding.Bmp280Calibration
module.exports.Calibration = nativeBinding.Calibration
module.exports.CdrReader = nativeBinding.CdrReader
module.exports.CdrWriter = nativeBinding.CdrWriter
module.exports.CoapClient = nativeBinding.CoapClient
module.exports.CobsDecoder = nativeBinding.CobsDecoder
module.exports.CommandProtocol = nativeBinding.CommandProtocol
module.exports.Controller = nativeBinding.Controller
module.exports.Debounce = nativeBinding.Debounce
module.exports.Depletion = nativeBinding.Depletion
module.exports.DeviceIdentity = nativeBinding.DeviceIdentity
module.exports.Dialect = nativeBinding.Dialect
module.exports.DutyCycle = nativeBinding.DutyCycle
module.exports.EventBus = nativeBinding.EventBus
module.exports.Geofence = nativeBinding.Geofence
module.exports.ImageVerifier = nativeBinding.ImageVerifier
module.exports.Kalman = nativeBinding.Kalman
module.exports.Ladder = nativeBinding.Ladder
module.exports.LoopbackBroker = nativeBinding.LoopbackBroker
module.exports.LoopbackTransport = nativeBinding.LoopbackTransport
module.exports.LoraChannelPlan = nativeBinding.LoraChannelPlan
module.exports.LoraPlanBuilder = nativeBinding.LoraPlanBuilder
module.exports.LorawanDevice = nativeBinding.LorawanDevice
module.exports.LorawanJoinAccept = nativeBinding.LorawanJoinAccept
module.exports.LorawanSession = nativeBinding.LorawanSession
module.exports.MavlinkFrame = nativeBinding.MavlinkFrame
module.exports.MavlinkMessage = nativeBinding.MavlinkMessage
module.exports.MavlinkParser = nativeBinding.MavlinkParser
module.exports.MavlinkSigner = nativeBinding.MavlinkSigner
module.exports.MavlinkVerifier = nativeBinding.MavlinkVerifier
module.exports.Median = nativeBinding.Median
module.exports.MessageSchema = nativeBinding.MessageSchema
module.exports.MessageSchemaBuilder = nativeBinding.MessageSchemaBuilder
module.exports.MissionReceiver = nativeBinding.MissionReceiver
module.exports.MissionSender = nativeBinding.MissionSender
module.exports.MqttClient = nativeBinding.MqttClient
module.exports.Pid = nativeBinding.Pid
module.exports.PowerPlan = nativeBinding.PowerPlan
module.exports.Profile = nativeBinding.Profile
module.exports.Quantizer = nativeBinding.Quantizer
module.exports.RadioDutyCycle = nativeBinding.RadioDutyCycle
module.exports.Ramp = nativeBinding.Ramp
module.exports.ReceiverStep = nativeBinding.ReceiverStep
module.exports.RecordingActuatorHandle = nativeBinding.RecordingActuatorHandle
module.exports.Replay = nativeBinding.Replay
module.exports.Reporter = nativeBinding.Reporter
module.exports.Router = nativeBinding.Router
module.exports.SeenPackets = nativeBinding.SeenPackets
module.exports.SenderStep = nativeBinding.SenderStep
module.exports.Session = nativeBinding.Session
module.exports.Signals = nativeBinding.Signals
module.exports.CanSignals = nativeBinding.CanSignals
module.exports.SimulatedRobot = nativeBinding.SimulatedRobot
module.exports.SimulatedSensor = nativeBinding.SimulatedSensor
module.exports.SlipDecoder = nativeBinding.SlipDecoder
module.exports.Smoother = nativeBinding.Smoother
module.exports.Stepper = nativeBinding.Stepper
module.exports.Store = nativeBinding.Store
module.exports.Surge = nativeBinding.Surge
module.exports.Thermostat = nativeBinding.Thermostat
module.exports.Transport = nativeBinding.Transport
module.exports.Trend = nativeBinding.Trend
module.exports.Trigger = nativeBinding.Trigger
module.exports.Updater = nativeBinding.Updater
module.exports.Window = nativeBinding.Window
module.exports.ads1115ConfigBits = nativeBinding.ads1115ConfigBits
module.exports.ads1115ConfigFromBits = nativeBinding.ads1115ConfigFromBits
module.exports.ads1115FullScaleMicrovolts = nativeBinding.ads1115FullScaleMicrovolts
module.exports.ads1115SamplesPerSecond = nativeBinding.ads1115SamplesPerSecond
module.exports.ads1115ToNanovolts = nativeBinding.ads1115ToNanovolts
module.exports.ads1115ToVolts = nativeBinding.ads1115ToVolts
module.exports.AlertKind = nativeBinding.AlertKind
module.exports.bearingBetween = nativeBinding.bearingBetween
module.exports.bmp280ConfigBits = nativeBinding.bmp280ConfigBits
module.exports.bmp280ConfigFromBits = nativeBinding.bmp280ConfigFromBits
module.exports.bmp280CtrlMeasBits = nativeBinding.bmp280CtrlMeasBits
module.exports.bmp280CtrlMeasFromBits = nativeBinding.bmp280CtrlMeasFromBits
module.exports.bmp280ImageUpdating = nativeBinding.bmp280ImageUpdating
module.exports.bmp280MeasurementBytes = nativeBinding.bmp280MeasurementBytes
module.exports.bmp280Measuring = nativeBinding.bmp280Measuring
module.exports.bmp280OversamplingFactor = nativeBinding.bmp280OversamplingFactor
module.exports.bmp280ParseMeasurement = nativeBinding.bmp280ParseMeasurement
module.exports.bmp280PressureSkipped = nativeBinding.bmp280PressureSkipped
module.exports.bmp280StandbyMicros = nativeBinding.bmp280StandbyMicros
module.exports.bmp280TemperatureSkipped = nativeBinding.bmp280TemperatureSkipped
module.exports.BootAction = nativeBinding.BootAction
module.exports.BoundaryState = nativeBinding.BoundaryState
module.exports.canDlcToLen = nativeBinding.canDlcToLen
module.exports.canFdFrame = nativeBinding.canFdFrame
module.exports.canFrame = nativeBinding.canFrame
module.exports.canLenToDlc = nativeBinding.canLenToDlc
module.exports.canRemoteFrame = nativeBinding.canRemoteFrame
module.exports.cborToJsonBytes = nativeBinding.cborToJsonBytes
module.exports.COBS_DELIMITER = nativeBinding.COBS_DELIMITER
module.exports.cobsDecode = nativeBinding.cobsDecode
module.exports.cobsEncode = nativeBinding.cobsEncode
module.exports.cobsMaxEncodedLen = nativeBinding.cobsMaxEncodedLen
module.exports.ControlKind = nativeBinding.ControlKind
module.exports.deadband = nativeBinding.deadband
module.exports.decodeDeltaSamples = nativeBinding.decodeDeltaSamples
module.exports.decodeManifest = nativeBinding.decodeManifest
module.exports.Delivery = nativeBinding.Delivery
module.exports.distanceBetween = nativeBinding.distanceBetween
module.exports.ds18b20BuildScratchpad = nativeBinding.ds18b20BuildScratchpad
module.exports.ds18b20Celsius = nativeBinding.ds18b20Celsius
module.exports.ds18b20ConfigByte = nativeBinding.ds18b20ConfigByte
module.exports.ds18b20Crc8 = nativeBinding.ds18b20Crc8
module.exports.ds18b20MaxConversionMicros = nativeBinding.ds18b20MaxConversionMicros
module.exports.ds18b20MicroCelsius = nativeBinding.ds18b20MicroCelsius
module.exports.ds18b20ParseScratchpad = nativeBinding.ds18b20ParseScratchpad
module.exports.ds18b20ResolutionBits = nativeBinding.ds18b20ResolutionBits
module.exports.ds18b20StepMicroCelsius = nativeBinding.ds18b20StepMicroCelsius
module.exports.Edge = nativeBinding.Edge
module.exports.encodeDeltaSamples = nativeBinding.encodeDeltaSamples
module.exports.encodeManifest = nativeBinding.encodeManifest
module.exports.EntityKindName = nativeBinding.EntityKindName
module.exports.envelopeBody = nativeBinding.envelopeBody
module.exports.fingerprint = nativeBinding.fingerprint
module.exports.ForwardAction = nativeBinding.ForwardAction
module.exports.hdc1080Celsius = nativeBinding.hdc1080Celsius
module.exports.hdc1080ConfigurationFromRegister = nativeBinding.hdc1080ConfigurationFromRegister
module.exports.hdc1080ConfigurationToRegister = nativeBinding.hdc1080ConfigurationToRegister
module.exports.hdc1080ConversionTimeMicros = nativeBinding.hdc1080ConversionTimeMicros
module.exports.hdc1080HumidityConversionMicros = nativeBinding.hdc1080HumidityConversionMicros
module.exports.hdc1080HumidityRegister = nativeBinding.hdc1080HumidityRegister
module.exports.hdc1080MeasurementBytes = nativeBinding.hdc1080MeasurementBytes
module.exports.hdc1080MeasurementFromPhysical = nativeBinding.hdc1080MeasurementFromPhysical
module.exports.hdc1080MilliCelsius = nativeBinding.hdc1080MilliCelsius
module.exports.hdc1080MilliPercent = nativeBinding.hdc1080MilliPercent
module.exports.hdc1080ParseMeasurement = nativeBinding.hdc1080ParseMeasurement
module.exports.hdc1080RelativeHumidity = nativeBinding.hdc1080RelativeHumidity
module.exports.hdc1080SerialId = nativeBinding.hdc1080SerialId
module.exports.hdc1080SerialIdRegisters = nativeBinding.hdc1080SerialIdRegisters
module.exports.hdc1080TemperatureConversionMicros = nativeBinding.hdc1080TemperatureConversionMicros
module.exports.hdc1080TemperatureRegister = nativeBinding.hdc1080TemperatureRegister
module.exports.hkdfSha256Expand = nativeBinding.hkdfSha256Expand
module.exports.hmacSha256Digest = nativeBinding.hmacSha256Digest
module.exports.I2C_RESERVED_BELOW = nativeBinding.I2C_RESERVED_BELOW
module.exports.I2C_RESERVED_FROM = nativeBinding.I2C_RESERVED_FROM
module.exports.i2cAddressFrame = nativeBinding.i2cAddressFrame
module.exports.i2cAddressFrameLen = nativeBinding.i2cAddressFrameLen
module.exports.i2cAddressIsGeneralCall = nativeBinding.i2cAddressIsGeneralCall
module.exports.i2cAddressIsReserved = nativeBinding.i2cAddressIsReserved
module.exports.imageDigest = nativeBinding.imageDigest
module.exports.ina219BusMillivolts = nativeBinding.ina219BusMillivolts
module.exports.ina219BusRegister = nativeBinding.ina219BusRegister
module.exports.ina219Calibration = nativeBinding.ina219Calibration
module.exports.ina219ConversionReady = nativeBinding.ina219ConversionReady
module.exports.ina219CurrentMicroamps = nativeBinding.ina219CurrentMicroamps
module.exports.ina219CurrentRegister = nativeBinding.ina219CurrentRegister
module.exports.ina219MathOverflow = nativeBinding.ina219MathOverflow
module.exports.ina219MinimumCurrentLsbMicroamps = nativeBinding.ina219MinimumCurrentLsbMicroamps
module.exports.ina219PowerMicrowatts = nativeBinding.ina219PowerMicrowatts
module.exports.ina219PowerRegister = nativeBinding.ina219PowerRegister
module.exports.ina219ShuntMicrovolts = nativeBinding.ina219ShuntMicrovolts
module.exports.ina219ShuntRegister = nativeBinding.ina219ShuntRegister
module.exports.ina226ActiveAlertFunction = nativeBinding.ina226ActiveAlertFunction
module.exports.ina226Address = nativeBinding.ina226Address
module.exports.Ina226AlertFunction = nativeBinding.Ina226AlertFunction
module.exports.ina226AveragingSamples = nativeBinding.ina226AveragingSamples
module.exports.ina226BusMicrovolts = nativeBinding.ina226BusMicrovolts
module.exports.ina226BusRegister = nativeBinding.ina226BusRegister
module.exports.ina226BusVolts = nativeBinding.ina226BusVolts
module.exports.ina226Calibration = nativeBinding.ina226Calibration
module.exports.ina226ConfigFromRegister = nativeBinding.ina226ConfigFromRegister
module.exports.ina226ConfigToRegister = nativeBinding.ina226ConfigToRegister
module.exports.ina226ConversionMicros = nativeBinding.ina226ConversionMicros
module.exports.ina226CurrentAmps = nativeBinding.ina226CurrentAmps
module.exports.ina226CurrentMicroamps = nativeBinding.ina226CurrentMicroamps
module.exports.ina226CurrentRegister = nativeBinding.ina226CurrentRegister
module.exports.ina226CurrentRegisterFromShunt = nativeBinding.ina226CurrentRegisterFromShunt
module.exports.ina226DieId = nativeBinding.ina226DieId
module.exports.ina226Identify = nativeBinding.ina226Identify
module.exports.ina226IsContinuous = nativeBinding.ina226IsContinuous
module.exports.ina226MaskEnableFromRegister = nativeBinding.ina226MaskEnableFromRegister
module.exports.ina226MaskEnableToRegister = nativeBinding.ina226MaskEnableToRegister
module.exports.ina226MeasuresBus = nativeBinding.ina226MeasuresBus
module.exports.ina226MeasuresShunt = nativeBinding.ina226MeasuresShunt
module.exports.ina226MinimumCurrentLsbMicroamps = nativeBinding.ina226MinimumCurrentLsbMicroamps
module.exports.ina226PowerMicrowatts = nativeBinding.ina226PowerMicrowatts
module.exports.ina226PowerRegister = nativeBinding.ina226PowerRegister
module.exports.ina226PowerRegisterFromCurrent = nativeBinding.ina226PowerRegisterFromCurrent
module.exports.ina226PowerWatts = nativeBinding.ina226PowerWatts
module.exports.ina226ShuntMillivolts = nativeBinding.ina226ShuntMillivolts
module.exports.ina226ShuntNanovolts = nativeBinding.ina226ShuntNanovolts
module.exports.ina226ShuntRegister = nativeBinding.ina226ShuntRegister
module.exports.ina226UpdateMicros = nativeBinding.ina226UpdateMicros
module.exports.J1939_BROADCAST_ADDRESS = nativeBinding.J1939_BROADCAST_ADDRESS
module.exports.J1939_NOT_AVAILABLE = nativeBinding.J1939_NOT_AVAILABLE
module.exports.J1939_PRIORITY_CONTROL = nativeBinding.J1939_PRIORITY_CONTROL
module.exports.J1939_PRIORITY_DEFAULT = nativeBinding.J1939_PRIORITY_DEFAULT
module.exports.J1939_PRIORITY_LOWEST = nativeBinding.J1939_PRIORITY_LOWEST
module.exports.j1939Broadcast = nativeBinding.j1939Broadcast
module.exports.j1939Compose = nativeBinding.j1939Compose
module.exports.j1939Decode = nativeBinding.j1939Decode
module.exports.jsonToCborBytes = nativeBinding.jsonToCborBytes
module.exports.keyexprCanonize = nativeBinding.keyexprCanonize
module.exports.keyexprIsCanon = nativeBinding.keyexprIsCanon
module.exports.keyexprIsValid = nativeBinding.keyexprIsValid
module.exports.keyexprMatches = nativeBinding.keyexprMatches
module.exports.Level = nativeBinding.Level
module.exports.LinkCost = nativeBinding.LinkCost
module.exports.linkCostThreshold = nativeBinding.linkCostThreshold
module.exports.loraAirtimeUs = nativeBinding.loraAirtimeUs
module.exports.LoraChannelSet = nativeBinding.LoraChannelSet
module.exports.loraDemodulatorSnrDb = nativeBinding.loraDemodulatorSnrDb
module.exports.LoraDirection = nativeBinding.LoraDirection
module.exports.loraEirpDbm = nativeBinding.loraEirpDbm
module.exports.loraFccMaxConductedDbm = nativeBinding.loraFccMaxConductedDbm
module.exports.loraFreeSpaceLossDb = nativeBinding.loraFreeSpaceLossDb
module.exports.loraFresnelRadiusMm = nativeBinding.loraFresnelRadiusMm
module.exports.loraLinkBudgetDefault = nativeBinding.loraLinkBudgetDefault
module.exports.loraLinkDefault = nativeBinding.loraLinkDefault
module.exports.loraMarginDb = nativeBinding.loraMarginDb
module.exports.loraMaxPathLossDb = nativeBinding.loraMaxPathLossDb
module.exports.loraMaxTransmitPowerDbm = nativeBinding.loraMaxTransmitPowerDbm
module.exports.loraMinOffTimeUs = nativeBinding.loraMinOffTimeUs
module.exports.LoraModulation = nativeBinding.LoraModulation
module.exports.loraNoiseFloorDbm = nativeBinding.loraNoiseFloorDbm
module.exports.LoraPayloadTable = nativeBinding.LoraPayloadTable
module.exports.loraReceivedDbm = nativeBinding.loraReceivedDbm
module.exports.LoraRegion = nativeBinding.LoraRegion
module.exports.loraSensitivityDbm = nativeBinding.loraSensitivityDbm
module.exports.loraSymbolTimeUs = nativeBinding.loraSymbolTimeUs
module.exports.LORAWAN_MAX_FRAME = nativeBinding.LORAWAN_MAX_FRAME
module.exports.LORAWAN_MAX_PAYLOAD = nativeBinding.LORAWAN_MAX_PAYLOAD
module.exports.LorawanDirection = nativeBinding.LorawanDirection
module.exports.lorawanGrantAccept = nativeBinding.lorawanGrantAccept
module.exports.lorawanGrantSession = nativeBinding.lorawanGrantSession
module.exports.LorawanMessageType = nativeBinding.LorawanMessageType
module.exports.lorawanParseHeader = nativeBinding.lorawanParseHeader
module.exports.lorawanParseJoinRequest = nativeBinding.lorawanParseJoinRequest
module.exports.MAVLINK_DEFAULT_TIMESTAMP_WINDOW = nativeBinding.MAVLINK_DEFAULT_TIMESTAMP_WINDOW
module.exports.MAVLINK_FIELD_CHAR = nativeBinding.MAVLINK_FIELD_CHAR
module.exports.MAVLINK_FIELD_DOUBLE = nativeBinding.MAVLINK_FIELD_DOUBLE
module.exports.MAVLINK_FIELD_FLOAT = nativeBinding.MAVLINK_FIELD_FLOAT
module.exports.MAVLINK_FIELD_INT16 = nativeBinding.MAVLINK_FIELD_INT16
module.exports.MAVLINK_FIELD_INT32 = nativeBinding.MAVLINK_FIELD_INT32
module.exports.MAVLINK_FIELD_INT64 = nativeBinding.MAVLINK_FIELD_INT64
module.exports.MAVLINK_FIELD_INT8 = nativeBinding.MAVLINK_FIELD_INT8
module.exports.MAVLINK_FIELD_UINT16 = nativeBinding.MAVLINK_FIELD_UINT16
module.exports.MAVLINK_FIELD_UINT32 = nativeBinding.MAVLINK_FIELD_UINT32
module.exports.MAVLINK_FIELD_UINT64 = nativeBinding.MAVLINK_FIELD_UINT64
module.exports.MAVLINK_FIELD_UINT8 = nativeBinding.MAVLINK_FIELD_UINT8
module.exports.MAVLINK_KEY_LEN = nativeBinding.MAVLINK_KEY_LEN
module.exports.MAVLINK_MAX_FRAME = nativeBinding.MAVLINK_MAX_FRAME
module.exports.MAVLINK_MAX_PAYLOAD = nativeBinding.MAVLINK_MAX_PAYLOAD
module.exports.MAVLINK_MAX_RETRIES = nativeBinding.MAVLINK_MAX_RETRIES
module.exports.MAVLINK_SIGNATURE_LEN = nativeBinding.MAVLINK_SIGNATURE_LEN
module.exports.MAVLINK_TYPEMASK_ACCELERATION = nativeBinding.MAVLINK_TYPEMASK_ACCELERATION
module.exports.MAVLINK_TYPEMASK_FORCE = nativeBinding.MAVLINK_TYPEMASK_FORCE
module.exports.MAVLINK_TYPEMASK_POSITION = nativeBinding.MAVLINK_TYPEMASK_POSITION
module.exports.MAVLINK_TYPEMASK_VELOCITY = nativeBinding.MAVLINK_TYPEMASK_VELOCITY
module.exports.MAVLINK_TYPEMASK_YAW = nativeBinding.MAVLINK_TYPEMASK_YAW
module.exports.MAVLINK_TYPEMASK_YAW_RATE = nativeBinding.MAVLINK_TYPEMASK_YAW_RATE
module.exports.mavlinkCrc16Mcrf4Xx = nativeBinding.mavlinkCrc16Mcrf4Xx
module.exports.mavlinkKnownCrcExtra = nativeBinding.mavlinkKnownCrcExtra
module.exports.mavlinkKnownMessages = nativeBinding.mavlinkKnownMessages
module.exports.mavlinkMessageCrcExtra = nativeBinding.mavlinkMessageCrcExtra
module.exports.mavlinkOffboardGlobalPosition = nativeBinding.mavlinkOffboardGlobalPosition
module.exports.mavlinkOffboardLocalPosition = nativeBinding.mavlinkOffboardLocalPosition
module.exports.mavlinkOffboardLocalVelocity = nativeBinding.mavlinkOffboardLocalVelocity
module.exports.mavlinkOffboardTypeMask = nativeBinding.mavlinkOffboardTypeMask
module.exports.mavlinkTimestampFromUnixMicros = nativeBinding.mavlinkTimestampFromUnixMicros
module.exports.MavlinkVersion = nativeBinding.MavlinkVersion
module.exports.MESH_BROADCAST = nativeBinding.MESH_BROADCAST
module.exports.MESH_DEFAULT_HOP_LIMIT = nativeBinding.MESH_DEFAULT_HOP_LIMIT
module.exports.MESH_HEADER_LEN = nativeBinding.MESH_HEADER_LEN
module.exports.MESH_MAX_FRAME = nativeBinding.MESH_MAX_FRAME
module.exports.MESH_MAX_PAYLOAD = nativeBinding.MESH_MAX_PAYLOAD
module.exports.MESH_SEEN_DEFAULT_CAPACITY = nativeBinding.MESH_SEEN_DEFAULT_CAPACITY
module.exports.meshBroadcastFrame = nativeBinding.meshBroadcastFrame
module.exports.meshCrc16 = nativeBinding.meshCrc16
module.exports.meshFrame = nativeBinding.meshFrame
module.exports.meshParseFrame = nativeBinding.meshParseFrame
module.exports.meshRelayed = nativeBinding.meshRelayed
module.exports.modbusCoils = nativeBinding.modbusCoils
module.exports.modbusCrc16 = nativeBinding.modbusCrc16
module.exports.modbusParseFrame = nativeBinding.modbusParseFrame
module.exports.modbusRaw = nativeBinding.modbusRaw
module.exports.modbusReadCoils = nativeBinding.modbusReadCoils
module.exports.modbusReadDiscreteInputs = nativeBinding.modbusReadDiscreteInputs
module.exports.modbusReadHoldingRegisters = nativeBinding.modbusReadHoldingRegisters
module.exports.modbusReadHoldingRegistersReply = nativeBinding.modbusReadHoldingRegistersReply
module.exports.modbusReadInputRegisters = nativeBinding.modbusReadInputRegisters
module.exports.modbusReadInputRegistersReply = nativeBinding.modbusReadInputRegistersReply
module.exports.modbusRegisters = nativeBinding.modbusRegisters
module.exports.modbusWriteMultipleCoils = nativeBinding.modbusWriteMultipleCoils
module.exports.modbusWriteMultipleRegisters = nativeBinding.modbusWriteMultipleRegisters
module.exports.modbusWriteSingleCoil = nativeBinding.modbusWriteSingleCoil
module.exports.modbusWriteSingleRegister = nativeBinding.modbusWriteSingleRegister
module.exports.openDelegation = nativeBinding.openDelegation
module.exports.opt3001ConfigBits = nativeBinding.opt3001ConfigBits
module.exports.opt3001ConfigFromBits = nativeBinding.opt3001ConfigFromBits
module.exports.opt3001ConversionMillis = nativeBinding.opt3001ConversionMillis
module.exports.opt3001FaultCount = nativeBinding.opt3001FaultCount
module.exports.opt3001FullScaleMilliLux = nativeBinding.opt3001FullScaleMilliLux
module.exports.opt3001IsAutomaticRange = nativeBinding.opt3001IsAutomaticRange
module.exports.opt3001LsbMilliLux = nativeBinding.opt3001LsbMilliLux
module.exports.opt3001Lux = nativeBinding.opt3001Lux
module.exports.opt3001MilliLux = nativeBinding.opt3001MilliLux
module.exports.opt3001RawFromMilliLux = nativeBinding.opt3001RawFromMilliLux
module.exports.opt3001WordFromBytes = nativeBinding.opt3001WordFromBytes
module.exports.opt3001WordToBytes = nativeBinding.opt3001WordToBytes
module.exports.PCA9685_CHANNELS = nativeBinding.PCA9685_CHANNELS
module.exports.PCA9685_COUNTS = nativeBinding.PCA9685_COUNTS
module.exports.PCA9685_INTERNAL_OSC_HZ = nativeBinding.PCA9685_INTERNAL_OSC_HZ
module.exports.pca9685ChannelRegister = nativeBinding.pca9685ChannelRegister
module.exports.pca9685FrequencyForPrescale = nativeBinding.pca9685FrequencyForPrescale
module.exports.pca9685PrescaleForFrequency = nativeBinding.pca9685PrescaleForFrequency
module.exports.PinEdge = nativeBinding.PinEdge
module.exports.pinEdgeTriggeredBy = nativeBinding.pinEdgeTriggeredBy
module.exports.PinLevel = nativeBinding.PinLevel
module.exports.pinLevelFromBool = nativeBinding.pinLevelFromBool
module.exports.pinLevelInverted = nativeBinding.pinLevelInverted
module.exports.PinPolarity = nativeBinding.PinPolarity
module.exports.pinPolarityIsAsserted = nativeBinding.pinPolarityIsAsserted
module.exports.pinPolarityLevel = nativeBinding.pinPolarityLevel
module.exports.PowerMode = nativeBinding.PowerMode
module.exports.pwmCounts = nativeBinding.pwmCounts
module.exports.pwmDuty = nativeBinding.pwmDuty
module.exports.pwmFromCounts = nativeBinding.pwmFromCounts
module.exports.pwmFullOff = nativeBinding.pwmFullOff
module.exports.pwmFullOn = nativeBinding.pwmFullOn
module.exports.pwmServo = nativeBinding.pwmServo
module.exports.Qos = nativeBinding.Qos
module.exports.Reliability = nativeBinding.Reliability
module.exports.Role = nativeBinding.Role
module.exports.ros2DdsTopic = nativeBinding.ros2DdsTopic
module.exports.ros2DdsTypeName = nativeBinding.ros2DdsTypeName
module.exports.ros2EntityKey = nativeBinding.ros2EntityKey
module.exports.ros2EntityKindPrefix = nativeBinding.ros2EntityKindPrefix
module.exports.ros2IsFullyQualified = nativeBinding.ros2IsFullyQualified
module.exports.ros2IsValidName = nativeBinding.ros2IsValidName
module.exports.ros2PercentMangle = nativeBinding.ros2PercentMangle
module.exports.ros2TwistFromCdr = nativeBinding.ros2TwistFromCdr
module.exports.ros2TwistToCdr = nativeBinding.ros2TwistToCdr
module.exports.ros2TypeHashDigest = nativeBinding.ros2TypeHashDigest
module.exports.ROUTING_DEFAULT_CAPACITY = nativeBinding.ROUTING_DEFAULT_CAPACITY
module.exports.scd4xAllowedDuringMeasurement = nativeBinding.scd4xAllowedDuringMeasurement
module.exports.scd4xAmbientPressurePascals = nativeBinding.scd4xAmbientPressurePascals
module.exports.scd4xAmbientPressureWord = nativeBinding.scd4xAmbientPressureWord
module.exports.scd4xAutomaticSelfCalibrationEnabled = nativeBinding.scd4xAutomaticSelfCalibrationEnabled
module.exports.scd4xAutomaticSelfCalibrationWord = nativeBinding.scd4xAutomaticSelfCalibrationWord
module.exports.scd4xCelsius = nativeBinding.scd4xCelsius
module.exports.scd4xCommandFrame = nativeBinding.scd4xCommandFrame
module.exports.scd4xCrc = nativeBinding.scd4xCrc
module.exports.scd4xDataReady = nativeBinding.scd4xDataReady
module.exports.scd4xForcedRecalibrationCorrectionPpm = nativeBinding.scd4xForcedRecalibrationCorrectionPpm
module.exports.scd4xForcedRecalibrationWord = nativeBinding.scd4xForcedRecalibrationWord
module.exports.scd4xHumidityMilliPercent = nativeBinding.scd4xHumidityMilliPercent
module.exports.scd4xHumidityRaw = nativeBinding.scd4xHumidityRaw
module.exports.scd4xMaxDurationMs = nativeBinding.scd4xMaxDurationMs
module.exports.scd4xMeasurementBytes = nativeBinding.scd4xMeasurementBytes
module.exports.scd4xMeasurementFromPhysical = nativeBinding.scd4xMeasurementFromPhysical
module.exports.scd4xMilliCelsius = nativeBinding.scd4xMilliCelsius
module.exports.scd4xParseMeasurement = nativeBinding.scd4xParseMeasurement
module.exports.scd4xRelativeHumidityPercent = nativeBinding.scd4xRelativeHumidityPercent
module.exports.scd4xSelfTestPassed = nativeBinding.scd4xSelfTestPassed
module.exports.scd4xSerialNumber = nativeBinding.scd4xSerialNumber
module.exports.scd4xSerialNumberFrame = nativeBinding.scd4xSerialNumberFrame
module.exports.scd4xTemperatureOffsetMilliCelsius = nativeBinding.scd4xTemperatureOffsetMilliCelsius
module.exports.scd4xTemperatureOffsetWord = nativeBinding.scd4xTemperatureOffsetWord
module.exports.scd4xTemperatureRaw = nativeBinding.scd4xTemperatureRaw
module.exports.scd4xWord = nativeBinding.scd4xWord
module.exports.scd4xWordFrame = nativeBinding.scd4xWordFrame
module.exports.scd4xWriteFrame = nativeBinding.scd4xWriteFrame
module.exports.sht3xCelsius = nativeBinding.sht3xCelsius
module.exports.sht3xCrc = nativeBinding.sht3xCrc
module.exports.sht3xFahrenheit = nativeBinding.sht3xFahrenheit
module.exports.sht3xHumidityRawFromMilliPercent = nativeBinding.sht3xHumidityRawFromMilliPercent
module.exports.sht3xHumidityRawFromRelativeHumidity = nativeBinding.sht3xHumidityRawFromRelativeHumidity
module.exports.sht3xIntervalMicros = nativeBinding.sht3xIntervalMicros
module.exports.sht3xMaxMeasurementMicros = nativeBinding.sht3xMaxMeasurementMicros
module.exports.sht3xMeasurementBytes = nativeBinding.sht3xMeasurementBytes
module.exports.sht3xMilliCelsius = nativeBinding.sht3xMilliCelsius
module.exports.sht3xMilliFahrenheit = nativeBinding.sht3xMilliFahrenheit
module.exports.sht3xMilliPercent = nativeBinding.sht3xMilliPercent
module.exports.sht3xParseMeasurement = nativeBinding.sht3xParseMeasurement
module.exports.sht3xParseStatus = nativeBinding.sht3xParseStatus
module.exports.sht3xPeriodic = nativeBinding.sht3xPeriodic
module.exports.Sht3xRate = nativeBinding.Sht3xRate
module.exports.sht3xRelativeHumidity = nativeBinding.sht3xRelativeHumidity
module.exports.Sht3xRepeatability = nativeBinding.Sht3xRepeatability
module.exports.sht3xSingleShot = nativeBinding.sht3xSingleShot
module.exports.sht3xStatusBytes = nativeBinding.sht3xStatusBytes
module.exports.sht3xStatusFromBits = nativeBinding.sht3xStatusFromBits
module.exports.sht3xTemperatureRawFromCelsius = nativeBinding.sht3xTemperatureRawFromCelsius
module.exports.sht3xTemperatureRawFromMilliCelsius = nativeBinding.sht3xTemperatureRawFromMilliCelsius
module.exports.sht3xTemperatureRawFromMilliFahrenheit = nativeBinding.sht3xTemperatureRawFromMilliFahrenheit
module.exports.sht3xTypicalMeasurementMicros = nativeBinding.sht3xTypicalMeasurementMicros
module.exports.sht3xWord = nativeBinding.sht3xWord
module.exports.sht3xWordBytes = nativeBinding.sht3xWordBytes
module.exports.signDelegation = nativeBinding.signDelegation
module.exports.signManifest = nativeBinding.signManifest
module.exports.SLIP_END = nativeBinding.SLIP_END
module.exports.SLIP_ESC = nativeBinding.SLIP_ESC
module.exports.SLIP_ESC_END = nativeBinding.SLIP_ESC_END
module.exports.SLIP_ESC_ESC = nativeBinding.SLIP_ESC_ESC
module.exports.slipDecode = nativeBinding.slipDecode
module.exports.slipEncode = nativeBinding.slipEncode
module.exports.slipMaxEncodedLen = nativeBinding.slipMaxEncodedLen
module.exports.SlotState = nativeBinding.SlotState
module.exports.spiModeClock = nativeBinding.spiModeClock
module.exports.spiModeFromClock = nativeBinding.spiModeFromClock
module.exports.StepDirection = nativeBinding.StepDirection
module.exports.StepDrive = nativeBinding.StepDrive
module.exports.stepperStepCount = nativeBinding.stepperStepCount
module.exports.stepperStepsForDegrees = nativeBinding.stepperStepsForDegrees
module.exports.SX126X_ERROR_ADC_CALIBRATION = nativeBinding.SX126X_ERROR_ADC_CALIBRATION
module.exports.SX126X_ERROR_IMAGE_CALIBRATION = nativeBinding.SX126X_ERROR_IMAGE_CALIBRATION
module.exports.SX126X_ERROR_PA_RAMP = nativeBinding.SX126X_ERROR_PA_RAMP
module.exports.SX126X_ERROR_PLL_CALIBRATION = nativeBinding.SX126X_ERROR_PLL_CALIBRATION
module.exports.SX126X_ERROR_PLL_LOCK = nativeBinding.SX126X_ERROR_PLL_LOCK
module.exports.SX126X_ERROR_RC13M_CALIBRATION = nativeBinding.SX126X_ERROR_RC13M_CALIBRATION
module.exports.SX126X_ERROR_RC64K_CALIBRATION = nativeBinding.SX126X_ERROR_RC64K_CALIBRATION
module.exports.SX126X_ERROR_XOSC_START = nativeBinding.SX126X_ERROR_XOSC_START
module.exports.SX126X_IRQ_ALL = nativeBinding.SX126X_IRQ_ALL
module.exports.SX126X_IRQ_CAD_DETECTED = nativeBinding.SX126X_IRQ_CAD_DETECTED
module.exports.SX126X_IRQ_CAD_DONE = nativeBinding.SX126X_IRQ_CAD_DONE
module.exports.SX126X_IRQ_CRC_ERROR = nativeBinding.SX126X_IRQ_CRC_ERROR
module.exports.SX126X_IRQ_HEADER_ERROR = nativeBinding.SX126X_IRQ_HEADER_ERROR
module.exports.SX126X_IRQ_HEADER_VALID = nativeBinding.SX126X_IRQ_HEADER_VALID
module.exports.SX126X_IRQ_LR_FHSS_HOP = nativeBinding.SX126X_IRQ_LR_FHSS_HOP
module.exports.SX126X_IRQ_PREAMBLE_DETECTED = nativeBinding.SX126X_IRQ_PREAMBLE_DETECTED
module.exports.SX126X_IRQ_RX_DONE = nativeBinding.SX126X_IRQ_RX_DONE
module.exports.SX126X_IRQ_SYNC_WORD_VALID = nativeBinding.SX126X_IRQ_SYNC_WORD_VALID
module.exports.SX126X_IRQ_TIMEOUT = nativeBinding.SX126X_IRQ_TIMEOUT
module.exports.SX126X_IRQ_TX_DONE = nativeBinding.SX126X_IRQ_TX_DONE
module.exports.SX126X_REGISTER_LORA_SYNC_WORD = nativeBinding.SX126X_REGISTER_LORA_SYNC_WORD
module.exports.SX126X_RX_CONTINUOUS = nativeBinding.SX126X_RX_CONTINUOUS
module.exports.SX126X_SYNC_WORD_PRIVATE = nativeBinding.SX126X_SYNC_WORD_PRIVATE
module.exports.SX126X_SYNC_WORD_PUBLIC = nativeBinding.SX126X_SYNC_WORD_PUBLIC
module.exports.Sx126xAmplifier = nativeBinding.Sx126xAmplifier
module.exports.sx126xCalibrateImage = nativeBinding.sx126xCalibrateImage
module.exports.Sx126xChipMode = nativeBinding.Sx126xChipMode
module.exports.sx126xClearIrqStatus = nativeBinding.sx126xClearIrqStatus
module.exports.Sx126xCommandStatus = nativeBinding.Sx126xCommandStatus
module.exports.sx126xDeviceErrors = nativeBinding.sx126xDeviceErrors
module.exports.sx126xFrequencyWord = nativeBinding.sx126xFrequencyWord
module.exports.sx126xGetDeviceErrors = nativeBinding.sx126xGetDeviceErrors
module.exports.sx126xGetIrqStatus = nativeBinding.sx126xGetIrqStatus
module.exports.sx126xGetPacketStatus = nativeBinding.sx126xGetPacketStatus
module.exports.sx126xGetRssiInst = nativeBinding.sx126xGetRssiInst
module.exports.sx126xGetRxBufferStatus = nativeBinding.sx126xGetRxBufferStatus
module.exports.sx126xGetStatus = nativeBinding.sx126xGetStatus
module.exports.sx126xImageCalibration = nativeBinding.sx126xImageCalibration
module.exports.sx126xIrq = nativeBinding.sx126xIrq
module.exports.sx126xPacketStatus = nativeBinding.sx126xPacketStatus
module.exports.sx126xRampTimeUs = nativeBinding.sx126xRampTimeUs
module.exports.sx126xReadBuffer = nativeBinding.sx126xReadBuffer
module.exports.sx126xReadRegister = nativeBinding.sx126xReadRegister
module.exports.sx126xRssiInstDbm = nativeBinding.sx126xRssiInstDbm
module.exports.sx126xRxBufferStatus = nativeBinding.sx126xRxBufferStatus
module.exports.sx126xSetDioIrqParams = nativeBinding.sx126xSetDioIrqParams
module.exports.sx126xSetLoraModulationParams = nativeBinding.sx126xSetLoraModulationParams
module.exports.sx126xSetLoraPacketParams = nativeBinding.sx126xSetLoraPacketParams
module.exports.sx126xSetPacketTypeLora = nativeBinding.sx126xSetPacketTypeLora
module.exports.sx126xSetPaConfig = nativeBinding.sx126xSetPaConfig
module.exports.sx126xSetRfFrequency = nativeBinding.sx126xSetRfFrequency
module.exports.sx126xSetRx = nativeBinding.sx126xSetRx
module.exports.sx126xSetRxContinuous = nativeBinding.sx126xSetRxContinuous
module.exports.sx126xSetSleep = nativeBinding.sx126xSetSleep
module.exports.sx126xSetStandby = nativeBinding.sx126xSetStandby
module.exports.sx126xSetTx = nativeBinding.sx126xSetTx
module.exports.sx126xSetTxParams = nativeBinding.sx126xSetTxParams
module.exports.sx126xStatus = nativeBinding.sx126xStatus
module.exports.sx126xTimeoutSteps = nativeBinding.sx126xTimeoutSteps
module.exports.sx126xTxPower = nativeBinding.sx126xTxPower
module.exports.sx126xTxPowerUnderCeiling = nativeBinding.sx126xTxPowerUnderCeiling
module.exports.sx126xWriteBuffer = nativeBinding.sx126xWriteBuffer
module.exports.sx126xWriteRegister = nativeBinding.sx126xWriteRegister
module.exports.tmp117AveragingConversions = nativeBinding.tmp117AveragingConversions
module.exports.tmp117AveragingMicros = nativeBinding.tmp117AveragingMicros
module.exports.tmp117Celsius = nativeBinding.tmp117Celsius
module.exports.tmp117ConfigBits = nativeBinding.tmp117ConfigBits
module.exports.tmp117ConfigFromBits = nativeBinding.tmp117ConfigFromBits
module.exports.tmp117CycleMicros = nativeBinding.tmp117CycleMicros
module.exports.tmp117CycleNominalMicros = nativeBinding.tmp117CycleNominalMicros
module.exports.tmp117DataReady = nativeBinding.tmp117DataReady
module.exports.tmp117DeviceId = nativeBinding.tmp117DeviceId
module.exports.tmp117EepromBusy = nativeBinding.tmp117EepromBusy
module.exports.tmp117EepromUnlockBusy = nativeBinding.tmp117EepromUnlockBusy
module.exports.tmp117HighAlert = nativeBinding.tmp117HighAlert
module.exports.tmp117LowAlert = nativeBinding.tmp117LowAlert
module.exports.tmp117MicroCelsius = nativeBinding.tmp117MicroCelsius
module.exports.tmp117NanoCelsius = nativeBinding.tmp117NanoCelsius
module.exports.tmp117RawFromCelsius = nativeBinding.tmp117RawFromCelsius
module.exports.tmp117RawFromMicroCelsius = nativeBinding.tmp117RawFromMicroCelsius
module.exports.tmp117Revision = nativeBinding.tmp117Revision
module.exports.tmp117TemperatureBytes = nativeBinding.tmp117TemperatureBytes
module.exports.tmp117TemperatureFromBytes = nativeBinding.tmp117TemperatureFromBytes
module.exports.UPDATE_FORMAT_RAW = nativeBinding.UPDATE_FORMAT_RAW
module.exports.UPDATE_STRUCTURE_VERSION = nativeBinding.UPDATE_STRUCTURE_VERSION
module.exports.verify = nativeBinding.verify
module.exports.verifyAuditChain = nativeBinding.verifyAuditChain
module.exports.verifyEnvelope = nativeBinding.verifyEnvelope
module.exports.verifyMessage = nativeBinding.verifyMessage
module.exports.version = nativeBinding.version
module.exports.Viz = nativeBinding.Viz
module.exports.WINDOW_CAPACITY = nativeBinding.WINDOW_CAPACITY
