/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Turns a raw sensor count into the units the reading is actually in. */
export declare class Calibration {
  /** Creates a calibration applying `raw * scale + offset`. */
  static linear(scale: number, offset: number): Calibration
  /** Creates a calibration fitted through two known reference points. */
  static twoPoint(rawLow: number, valueLow: number, rawHigh: number, valueHigh: number): Calibration
  /** Converts a raw reading into calibrated units. */
  apply(raw: number): number
}

/** Reassembles whole COBS frames from the chunks a serial port delivers. */
export declare class CobsDecoder {
  /** Creates an empty decoder, ready for the first chunk. */
  constructor()
  /** Feeds a chunk of the stream and returns every frame it completed. */
  feed(chunk: Buffer): Array<Buffer>
  /** Returns how many corrupt frames this decoder has discarded. */
  get discarded(): number
  /** Discards any partly assembled frame. */
  reset(): void
}

/** Stops a flickering input from acting until it has settled. */
export declare class Debounce {
  /** Creates a debouncer needing `samples` agreeing readings to change state. */
  constructor(samples: number, initial: boolean)
  /** Feeds a raw reading in and returns the settled state. */
  update(raw: boolean): boolean
  /** Returns the settled state without feeding in a reading. */
  state(): boolean
}

/** Warns before a falling level runs out, by projecting its rate of fall. */
export declare class Depletion {
  /** Creates an estimator that counts down to `threshold`. */
  constructor(threshold: number)
  /**
   * Records a level and returns the samples left before the threshold.
   *
   * Returns `null` while the level is steady or rising, and on the first
   * reading, when no rate of fall is known yet.
   */
  update(level: number): number | null
}

/** A device's private signing identity. */
export declare class DeviceIdentity {
  /** Creates an identity from a provisioned 32-byte secret seed. */
  constructor(seed: Buffer)
  /** Returns the public key matching this identity, safe to share. */
  publicKey(): Buffer
  /** Returns the short hex fingerprint of this identity, for logs and displays. */
  fingerprint(): string
  /** Signs a payload, returning the 64-byte detached signature. */
  sign(payload: Buffer): Buffer
}

/** Keeps a tracked point inside an area, and notices when it leaves. */
export declare class Geofence {
  /** Creates a circular fence of `radiusM` metres around `center`. */
  constructor(center: Coord, radiusM: number)
  /** Feeds a fix in and reports where it sits, including a single crossing. */
  update(point: Coord): BoundaryState
  /** Reports whether a fix lies inside, without recording a crossing. */
  contains(point: Coord): boolean
}

/**
 * Estimates a true value from noisy readings, trusting the model and the sensor
 * in proportion to how noisy each is.
 */
export declare class Kalman {
  /** Creates a filter from the process and measurement noise, and a first guess. */
  constructor(processNoise: number, measurementNoise: number, initial: number)
  /** Folds a reading in and returns the new estimate. */
  update(reading: number): number
  /** Returns the current estimate without folding in a reading. */
  estimate(): number
}

/** An MQTT client transport backed by the native pamoja core. */
export declare class MqttClient {
  /** Creates a disconnected client from the given options. */
  constructor(options: MqttClientOptions)
  /** Connects to the broker and starts the background event loop. */
  connect(): Promise<void>
  /** Publishes a payload to a topic. */
  publish(topic: string, payload: Buffer): Promise<void>
  /** Subscribes to a topic filter. */
  subscribe(topic: string): Promise<void>
  /**
   * Awaits the next message from any subscribed topic, or `null` once the
   * connection has ended.
   */
  recv(): Promise<MqttMessage | null>
  /** Reports whether the client currently holds an active connection. */
  isConnected(): Promise<boolean>
  /** Closes the connection and stops the background event loop. */
  disconnect(): Promise<void>
}

/** Holds a value at a setpoint by trading off present, past, and predicted error. */
export declare class Pid {
  /** Creates a controller with the given proportional, integral, derivative gains. */
  constructor(kp: number, ki: number, kd: number)
  /** Creates a controller whose output is clamped to `[min, max]`. */
  static withLimits(kp: number, ki: number, kd: number, min: number, max: number): Pid
  /** Advances the controller by one step and returns the control output. */
  update(setpoint: number, measurement: number, dt: number): number
  /** Clears the accumulated integral and last error. */
  reset(): void
}

/** Packs float readings to a fixed precision for a metered link. */
export declare class Quantizer {
  /**
   * Creates a quantizer whose `scale` sets the precision kept.
   *
   * A scale of `100` keeps two decimal places. It must be positive and finite,
   * and decoding must use the same scale the batch was encoded with.
   */
  constructor(scale: number)
  /** Quantizes and delta-encodes a batch of readings. */
  encode(readings: Array<number>): Buffer
  /** Decodes a batch back into readings, to within the quantizer's precision. */
  decode(bytes: Buffer): Array<number>
}

/** Limits how fast a value may change, so a load is never slammed. */
export declare class Ramp {
  /** Creates a limiter starting at `start` and moving at most `maxStep` a step. */
  constructor(start: number, maxStep: number)
  /** Moves one step toward `target` and returns the new value. */
  update(target: number): number
  /** Returns the current value. */
  value(): number
  /** Forces the value without rate limiting. */
  set(value: number): void
}

/** Reassembles whole SLIP frames from the chunks a serial port delivers. */
export declare class SlipDecoder {
  /** Creates an empty decoder, ready for the first chunk. */
  constructor()
  /** Feeds a chunk of the stream and returns every frame it completed. */
  feed(chunk: Buffer): Array<Buffer>
  /** Returns how many corrupt frames this decoder has discarded. */
  get discarded(): number
  /** Discards any partly assembled frame. */
  reset(): void
}

/** Smooths a noisy reading by weighting each new sample against the running value. */
export declare class Smoother {
  /** Creates a smoother whose `weight` sets how much each new sample counts. */
  constructor(weight: number)
  /** Folds a sample in and returns the smoothed value. */
  update(sample: number): number
  /** Returns the current value, or `null` before the first sample. */
  value(): number | null
  /** Clears the smoother back to its initial state. */
  reset(): void
}

/** Notices a step change between successive readings, such as a burst pipe. */
export declare class Surge {
  /** Creates a detector for rises of at least `limit` between readings. */
  static rising(limit: number): Surge
  /** Creates a detector for falls of at least `limit` between readings. */
  static falling(limit: number): Surge
  /** Feeds a value in and returns the size of a qualifying step, or `null`. */
  update(value: number): number | null
}

/** Switches a load on and off around a setpoint, with hysteresis to stop chatter. */
export declare class Thermostat {
  /** Creates a cooling thermostat, which switches on when the reading rises. */
  static cooling(setpoint: number, hysteresis: number): Thermostat
  /** Creates a heating thermostat, which switches on when the reading falls. */
  static heating(setpoint: number, hysteresis: number): Thermostat
  /** Feeds a reading in and returns whether the load should be on. */
  update(reading: number): boolean
  /** Reports the current output without feeding in a reading. */
  isOn(): boolean
}

/** Returns the initial bearing from one coordinate to another, in degrees. */
export declare function bearingBetween(from: Coord, to: Coord): number

/** Where a fix sits relative to a geofence, including the moment it crosses. */
export declare const enum BoundaryState {
  /** The fix is inside the fence and was inside before, or is the first fix inside. */
  Inside = 'Inside',
  /** The fix is outside the fence and was outside before, or is the first fix outside. */
  Outside = 'Outside',
  /** The fix just crossed from inside to outside: the moment to raise a breach alert. */
  Exited = 'Exited',
  /** The fix just crossed from outside back inside. */
  Entered = 'Entered'
}

/** Returns the payload length a data length code encodes. */
export declare function canDlcToLen(dlc: number): number

/** Builds a CAN-FD frame, which carries up to 64 bytes at the discrete CAN-FD lengths. */
export declare function canFdFrame(id: number, extended: boolean, data: Buffer): CanFrame

/** Builds a classic CAN 2.0 frame, which carries up to eight bytes. */
export declare function canFrame(id: number, extended: boolean, data: Buffer): CanFrame

/** A CAN frame: an identifier, its flags, and its payload. */
export interface CanFrame {
  /** The arbitration identifier, already masked to 11 or 29 bits. */
  id: number
  /** Whether the identifier is a 29-bit extended one. */
  extended: boolean
  /** Whether this is a CAN-FD frame rather than classic CAN 2.0. */
  fd: boolean
  /** Whether this is a remote transmission request, which carries no payload. */
  remote: boolean
  /** The data length: the payload length, or the length a remote frame requests. */
  len: number
  /** The data length code as it appears on the wire. */
  dlc: number
  /** The payload, empty for a remote frame. */
  data: Buffer
}

/** Returns the data length code that encodes a payload length. */
export declare function canLenToDlc(len: number): number

/** Builds a remote transmission request, which asks another node to send. */
export declare function canRemoteFrame(id: number, extended: boolean, len: number): CanFrame

/** Converts a CBOR document back into its JSON encoding. */
export declare function cborToJsonBytes(cbor: Buffer): Buffer

/** Reads the payload back out of a COBS frame. */
export declare function cobsDecode(frame: Buffer): Buffer

/** Frames a payload as a COBS packet, terminated by its zero delimiter. */
export declare function cobsEncode(payload: Buffer): Buffer

/** Returns the largest COBS frame a payload of this length can produce. */
export declare function cobsMaxEncodedLen(payloadLen: number): number

/** A latitude and longitude in degrees. */
export interface Coord {
  /** Degrees north of the equator, negative for south. */
  latitude: number
  /** Degrees east of the prime meridian, negative for west. */
  longitude: number
}

/** Suppresses movement within `width` of `center`, so noise does not act. */
export declare function deadband(value: number, center: number, width: number): number

/** Decodes a delta-encoded buffer back into its integer samples. */
export declare function decodeDeltaSamples(bytes: Buffer): Array<number>

/** Returns the great-circle distance between two coordinates, in metres. */
export declare function distanceBetween(from: Coord, to: Coord): number

/** Delta-encodes a series of integer samples into a compact buffer. */
export declare function encodeDeltaSamples(samples: Array<number>): Buffer

/** Returns the short hex fingerprint of a public key. */
export declare function fingerprint(publicKey: Buffer): string

/**
 * Returns the address bytes a controller puts on the bus for a transfer.
 *
 * A 7-bit address frames as the single byte `(address << 1) | r/w`; a 10-bit one
 * frames as two, the reserved `11110` prefix carrying the top two bits and the
 * read/write bit, then the low eight.
 */
export declare function i2cAddressFrame(address: number, tenBit: boolean, read: boolean): Buffer

/**
 * Returns how many bytes an address frame occupies: one for a 7-bit address, two
 * for a 10-bit one.
 */
export declare function i2cAddressFrameLen(address: number, tenBit: boolean): number

/**
 * Reports whether an address is the general call address `0x00`, the broadcast
 * every device on the bus listens to.
 */
export declare function i2cAddressIsGeneralCall(address: number, tenBit: boolean): boolean

/**
 * Reports whether a 7-bit address falls in a range the I2C specification reserves.
 *
 * UM10204 reserves `0x00..=0x07` and `0x78..=0x7F`, leaving `0x08..=0x77` for
 * ordinary devices. A 10-bit address is never reserved in this sense.
 */
export declare function i2cAddressIsReserved(address: number, tenBit: boolean): boolean

/**
 * Composes the extended CAN identifier a set of J1939 fields describes.
 *
 * The destination is used only for an addressed (PDU1) parameter group and
 * ignored for a broadcast (PDU2) one.
 */
export declare function j1939Compose(priority: number, pgn: number, source: number, destination: number): number

/**
 * Decodes the J1939 fields out of an extended CAN identifier.
 *
 * Returns `null` for a standard 11-bit identifier, which J1939 does not use.
 */
export declare function j1939Decode(id: number, extended: boolean): J1939Message | null

/** The fields J1939 packs into an extended CAN identifier. */
export interface J1939Message {
  /** The parameter group number, which names what the message carries. */
  pgn: number
  /** The message priority, 0 (highest) to 7. */
  priority: number
  /** The source address: the node that sent the message. */
  source: number
  /** The PDU format byte of the parameter group. */
  pduFormat: number
  /**
   * The destination address for an addressed (PDU1) message, or `null` for a
   * broadcast (PDU2) one.
   */
  destination?: number
  /** Whether the message is a broadcast. */
  broadcast: boolean
}

/** Converts a JSON document into its CBOR encoding, which is typically smaller. */
export declare function jsonToCborBytes(json: Buffer): Buffer

/** Reads `count` coils or discrete inputs out of a read-bits response PDU. */
export declare function modbusCoils(pdu: Buffer, count: number): Array<boolean>

/** Computes the CRC-16/MODBUS that every RTU frame ends with. */
export declare function modbusCrc16(bytes: Buffer): number

/** A received Modbus RTU frame whose CRC has been verified. */
export interface ModbusFrame {
  /** The unit (slave) address the frame is addressed to or came from. */
  address: number
  /**
   * The function code. An exception response carries the request's code with
   * its high bit set, as it appeared on the wire.
   */
  functionCode: number
  /**
   * The exception code a device reported, or `null` when the frame is not an
   * exception response.
   */
  exception?: number
  /**
   * The protocol data unit: the function code and its data, without the
   * address or the CRC.
   */
  pdu: Buffer
}

/** Parses a received RTU frame, verifying its CRC. */
export declare function modbusParseFrame(bytes: Buffer): ModbusFrame

/**
 * Builds a request frame from a raw function code and data.
 *
 * This is the escape hatch for the function codes the SDK does not name.
 */
export declare function modbusRaw(address: number, functionCode: number, data: Buffer): Buffer

/** Builds a read-coils request frame (function `0x01`). */
export declare function modbusReadCoils(address: number, start: number, count: number): Buffer

/** Builds a read-discrete-inputs request frame (function `0x02`). */
export declare function modbusReadDiscreteInputs(address: number, start: number, count: number): Buffer

/** Builds a read-holding-registers request frame (function `0x03`). */
export declare function modbusReadHoldingRegisters(address: number, start: number, count: number): Buffer

/** Builds a read-input-registers request frame (function `0x04`). */
export declare function modbusReadInputRegisters(address: number, start: number, count: number): Buffer

/** Reads the 16-bit registers out of a read-registers response PDU. */
export declare function modbusRegisters(pdu: Buffer): Array<number>

/** Builds a write-multiple-coils request frame (function `0x0F`). */
export declare function modbusWriteMultipleCoils(address: number, start: number, values: Array<boolean>): Buffer

/** Builds a write-multiple-registers request frame (function `0x10`). */
export declare function modbusWriteMultipleRegisters(address: number, start: number, values: Array<number>): Buffer

/** Builds a write-single-coil request frame (function `0x05`). */
export declare function modbusWriteSingleCoil(address: number, coil: number, on: boolean): Buffer

/** Builds a write-single-register request frame (function `0x06`). */
export declare function modbusWriteSingleRegister(address: number, register: number, value: number): Buffer

/** Connection settings for an [`MqttClient`]. */
export interface MqttClientOptions {
  /** The MQTT client identifier presented to the broker. */
  clientId: string
  /** The broker hostname or IP address. */
  host: string
  /** The broker TCP port, conventionally 1883 for plaintext MQTT. */
  port: number
  /** Keep-alive interval in seconds. Defaults to 30 when omitted. */
  keepAliveSecs?: number
  /** Bound on outstanding client requests. Defaults to 64 when omitted. */
  capacity?: number
  /** Default quality of service. Defaults to `AtLeastOnce` when omitted. */
  qos?: Qos
}

/** A message received from a subscribed topic. */
export interface MqttMessage {
  /** The topic the message was published to. */
  topic: string
  /** The raw payload bytes. */
  payload: Buffer
}

/** The signal transition that triggers a pin interrupt. */
export declare const enum PinEdge {
  /** A low-to-high transition. */
  Rising = 'Rising',
  /** A high-to-low transition. */
  Falling = 'Falling',
  /** Either transition. */
  Both = 'Both'
}

/** Reports whether a change from one level to another fires an interrupt trigger. */
export declare function pinEdgeTriggeredBy(edge: PinEdge, from: PinLevel, to: PinLevel): boolean

/** The physical voltage level on a pin. */
export declare const enum PinLevel {
  /** A low level, near ground. */
  Low = 'Low',
  /** A high level, near the supply voltage. */
  High = 'High'
}

/** Returns the level a boolean names. */
export declare function pinLevelFromBool(high: boolean): PinLevel

/** Returns the opposite level. */
export declare function pinLevelInverted(level: PinLevel): PinLevel

/** Whether a signal is asserted by a high or a low physical level. */
export declare const enum PinPolarity {
  /** A high level means asserted. */
  ActiveHigh = 'ActiveHigh',
  /** A low level means asserted, the wiring of most buttons and relay boards. */
  ActiveLow = 'ActiveLow'
}

/** Reports whether a physical level means the signal is asserted. */
export declare function pinPolarityIsAsserted(polarity: PinPolarity, level: PinLevel): boolean

/** Returns the physical level that represents a logical state under a polarity. */
export declare function pinPolarityLevel(polarity: PinPolarity, asserted: boolean): PinLevel

/** MQTT delivery guarantee, mirroring the protocol's quality-of-service levels. */
export declare const enum Qos {
  /** Fire and forget; the broker does not acknowledge delivery. */
  AtMostOnce = 'AtMostOnce',
  /** Delivered at least once and acknowledged. */
  AtLeastOnce = 'AtLeastOnce',
  /** Delivered exactly once via a four-step handshake. */
  ExactlyOnce = 'ExactlyOnce'
}

/** Reads the payload back out of a SLIP frame. */
export declare function slipDecode(frame: Buffer): Buffer

/** Frames a payload as a SLIP packet (RFC 1055). */
export declare function slipEncode(payload: Buffer): Buffer

/** Returns the largest SLIP frame a payload of this length can produce. */
export declare function slipMaxEncodedLen(payloadLen: number): number

/** The clock polarity and phase pair an SPI mode number names. */
export interface SpiClock {
  /** Whether the clock idles high (CPOL = 1), which is modes 2 and 3. */
  cpol: boolean
  /** Whether data is sampled on the trailing edge (CPHA = 1), which is modes 1 and 3. */
  cpha: boolean
}

/** Returns the `(CPOL, CPHA)` pair an SPI mode number names. */
export declare function spiModeClock(mode: number): SpiClock

/** Returns the SPI mode number a `(CPOL, CPHA)` pair names. */
export declare function spiModeFromClock(cpol: boolean, cpha: boolean): number

/**
 * Verifies that a signature covers a payload and was made by a public key.
 *
 * Returns `false` when the payload was altered or was signed by a different
 * device, and throws only when an argument is the wrong length.
 */
export declare function verify(publicKey: Buffer, payload: Buffer, signature: Buffer): boolean

/** Returns the version of the native pamoja module. */
export declare function version(): string
